/*
 * Gym Tracker — الترجمة الإنجليزية. المفتاح هو النص العربي كما يظهر على الشاشة، والقيمة الإنجليزي.
 * {0} {1}… = الأرقام اللي في النص بالترتيب. القيمة ممكن تكون دالة (للمفرد والجمع).
 * ما يشتغل إلا إذا كانت اللغة English (i18n.js).
 */
(function () {
  'use strict';
  if (!window.GymI18n) return;
  var n = function (x) { return Number(String(x).replace(/,/g, '')); };
  var pl = function (word, plural) { return function (x) { return x + ' ' + (n(x) === 1 ? word : (plural || word + 's')); }; };
  var t = function (s) { return window.GymI18n.tq(s); };

  GymI18n.addLists({
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
  });

  // words that can sit next to numbers in short labels ("60كجم×10", "BW−5كجم")
  // exercise names: "بنش بريس … (Barbell Bench Press)" — the short Arabic name alone maps to the English part
  GymI18n.addLazy(function () {
    if (!window.GymCatalog) return false;
    var d = {};
    GymCatalog.DEFAULT_EXERCISES.forEach(function (ex) {
      var m = /^(.+?)\s*\(([^()]*[A-Za-z][^()]*)\)\s*$/.exec(ex.name);
      if (m) d[m[1].trim()] = m[2].trim();
    });
    d['جهاز T-Bar Row'] = 'T-Bar Row Machine';
    GymI18n.add(d);
    return true;
  });
  GymI18n.addWords({ 'لكل': 'per', 'يد': 'hand', 'مساعدة': 'assist', 'إضافي': 'added', 'كجم': 'kg', 'باوند': 'lb', 'ث': 's', 'د': 'm', 'كم': 'km', 'طن': 't', 'سم': 'cm', 'عدات': 'reps', 'عدة': 'reps', 'جولات': 'sets', 'جولة': 'set', 'ثانية': 's', 'دقيقة': 'min' });
  GymI18n.add({
    /* ===== page, header, navigation ===== */
    'متتبع التمارين - Gym Tracker v11.0': 'Gym Tracker v11.0',
    'تطبيق تتبع التمارين الرياضية والسعرات الحرارية ومؤشرات القوة 1RM و RPE': 'Workout tracker for sets, calories and strength (1RM, RPE)',
    'سعرة تقديرية': 'est. kcal',
    'جاري ربط IndexedDB...': 'Connecting storage…',
    'محفوظ على هذا الجهاز ✓': 'Saved on this device ✓',
    'محفوظ محليًا — التخزين البديل ✓': 'Saved locally (backup storage) ✓',
    'التمرين': 'Workout',
    'إضافة تمرين': 'Add exercise',
    'التطور': 'Progress',
    'التحليل': 'Analysis',
    'البروفايل': 'Profile',
    'الإصدار 11.0': 'Version 11.0',

    /* ===== session card ===== */
    'جلسة التمرين الحالية': 'Current session',
    'لا توجد جلسة نشطة': 'No active session',
    'ابدأ جلسة ليتم حساب مدتها وملخصها بدقة': 'Start a session to track its duration and summary',
    'نوع الجلسة': 'Session type',
    'جلسة حرة': 'Free session',
    'يوم الدفع (Push)': 'Push day',
    'يوم السحب (Pull)': 'Pull day',
    'يوم الأرجل (Legs)': 'Leg day',
    'علوي (Upper)': 'Upper',
    'سفلي (Lower)': 'Lower',
    'ابدأ الجلسة': 'Start session',
    'استخدام السابقة كخطة': 'Reuse last session',
    'إنهاء وملخص': 'Finish & summary',
    'إنهاء وعرض الملخص': 'Finish & show summary',
    'إنهاء الجلسة': 'Finish session',
    'خطّط الجلسة: اختر تمارينك': 'Plan the session: pick exercises',
    'خطة الجلسة': 'Session plan',
    'اختر التمارين اللي ناوي عليها اليوم. تقدر تضيف غيرها أثناء الجلسة عادي.': 'Pick the exercises you plan to do today. You can still add others during the session.',
    'ابدأ بهذي الخطة': 'Start with this plan',
    'حفظ الخطة': 'Save plan',
    'عدّل الخطة': 'Edit plan',
    'تمرين واحد': '1 exercise',
    '{0} تمارين': pl('exercise'),
    '{0} تمرين': pl('exercise'),
    '{0} تمارِينَ': pl('exercise'),
    '0 تمارين': '0 exercises',
    '0 تمرين': '0 exercises',
    '0 تمارِينَ': '0 exercises',
    'الخطة: {0} من {1}': 'Plan: {0} of {1}',
    'الخطة: {0} تمارين. تقدر تضيف غيرها عادي': 'Plan: {0} exercises. You can still add others',
    'الخطة: تمرين واحد. تقدر تضيف غيرها عادي': 'Plan: 1 exercise. You can still add others',
    'اختر تمرين واحد على الأقل': 'Pick at least one exercise',
    'بدأت {0}': 'Started {0}',
    'جلسة {0}': 'Session {0}',
    'ملخص {0}': '{0} summary',
    'لديك جلسة نشطة بالفعل': 'You already have an active session',
    'لا توجد جلسة سابقة لنسخها': 'No previous session to copy',
    'تم تحميل {0} تمارين من الجلسة السابقة': function (x) { return 'Loaded ' + pl('exercise')(x) + ' from the last session'; },
    'مثل الجلسة السابقة': 'Same as last session',
    'قائمة جاهزة': 'Preset list',
    'تمرين بدون جلسة': 'Exercise without a session',
    'المدة الفعلية بالدقائق (تشمل الراحة والكارديو)': 'Actual duration in minutes (rest and cardio included)',
    'راجع المدة إذا تركت الجلسة مفتوحة بعد انتهاء تمرينك.': 'Check the duration if you left the session open after training.',
    'مدة الجلسة': 'Session duration',
    'مجموع مدة الكارديو أكبر من مدة الجلسة المسجلة': 'Total cardio time is longer than the session',
    'مدة الكارديو المسجلة أكبر من مدة الجلسة. صحح المدة أو تسجيل الكارديو.': 'Logged cardio is longer than the session. Fix the duration or the cardio entry.',
    'حدّث ملفات الموقع كاملة لفتح نافذة إنهاء الجلسة': 'Update all site files to open the finish-session window',
    'حدّث ملفات الموقع كاملة لفتح محرر السجل الجديد': 'Update all site files to open the new log editor',

    /* ===== exercise picker and lists ===== */
    'القوائم والفلاتر': 'Lists & filters',
    'كل التمارين': 'All exercises',
    '{0} نتيجة': pl('result'),
    'قوائم تمارين جاهزة:': 'Preset lists:',
    'الكل': 'All',
    'اختر التمرين:': 'Exercise:',
    'بحث سريع عن تمرين...': 'Quick search…',
    'بحث عن تمرين…': 'Search exercises…',
    'بحث في التمارين': 'Search exercises',
    'قائمة اختيار التمرين': 'Exercise list',
    'تم إظهار جميع التمارين': 'Showing all exercises',
    'تم عرض قائمة التمارين الجاهزة': 'Showing the preset list',
    'لا توجد تمارين تطابق خيارات البحث': 'No exercises match your search',
    'ما فيه تمرين بهذا الاسم': 'No exercise with that name',
    'أداء الجلسة السابقة:': 'Last session:',
    'لا يوجد أداء سابق مسجل لهذا التمرين': 'No previous sets for this exercise',
    'اختيار جولة من الأداء السابق': 'Pick a set from last time',
    'الجولة السابقة المراد تعبئتها:': 'Set to copy:',
    'تعبئة الجولة': 'Fill set',
    'تمت تعبئة الجولة المختارة؛ اضغط حفظ بعد أدائها': 'Set filled. Tap save after you do it',

    /* ===== suggestion ===== */
    'اقتراح اليوم': "Today's suggestion",
    'عبّي الاقتراح': 'Use suggestion',
    'تعبّى الاقتراح. عدّله لو تبي، وبعدها احفظ الجولة': 'Suggestion filled. Adjust it if you like, then save the set',
    'زد عدة وحدة.': 'Add one rep.',
    'كان فيك عدات باقية، زد عدة.': 'You had reps left, add a rep.',
    'ثبّت المساعدة وزد عدة.': 'Keep the assistance and add a rep.',
    'وصلت للفشل، ثبّت نفس المساعدة والعدات.': 'You hit failure. Keep the same assistance and reps.',
    'وصلت للفشل، ثبّت نفس العدات لين تسويها وفيك عدة باقية.': 'You hit failure. Keep the same reps until you finish them with a rep to spare.',
    'وصلت للفشل، فثبّت نفس الوزن والعدات لين تسويها وفيك عدة باقية.': 'You hit failure. Keep the same weight and reps until you finish them with a rep to spare.',
    'ما سجلت RIR، فالاقتراح على العدات: ثبّت الوزن وزد عدة.': 'No RIR logged, so this is based on reps: keep the weight and add a rep.',

    /* ===== load mode, weight, reps ===== */
    'طريقة تسجيل الحمل': 'Load type',
    'طريقة تسجيل الحمل:': 'Load type:',
    'وزن خارجي / بار / جهاز': 'External weight / bar / machine',
    'دمبل — الوزن لكل يد': 'Dumbbells (weight per hand)',
    'دمبل — لكل يد': 'Dumbbells (per hand)',
    'وزن الجسم فقط': 'Bodyweight only',
    'وزن الجسم + وزن إضافي': 'Bodyweight + added weight',
    'وزن الجسم + إضافي': 'Bodyweight + added',
    'وزن جسم + إضافي': 'Bodyweight + added',
    'وزن جسم بمساعدة': 'Assisted bodyweight',
    'تمرين بالوقت (مثل البلانك)': 'Timed (like a plank)',
    'تمرين بالوقت': 'Timed',
    'يسجل الوزن المدخل كما هو ويستخدمه في القوة والحجم.': 'Logs the weight as entered and uses it for strength and volume.',
    'الرقم هو وزن الدمبل الواحد؛ الحجم التدريبي يحسب اليدين ×2.': 'Enter one dumbbell; volume counts both hands (×2).',
    'يستخدم وزن جسمك من البروفايل. خانة الوزن يمكن تركها صفرًا.': 'Uses your bodyweight from the profile. The weight field can stay at zero.',
    'أدخل الوزن الإضافي فقط؛ الحمل الفعلي = وزن الجسم + الوزن الإضافي.': 'Enter the added weight only; actual load = bodyweight + added weight.',
    'أدخل مقدار المساعدة؛ التقدم يتحسن عندما تقل المساعدة.': 'Enter the assistance; less assistance means progress.',
    'للبلانك والتمارين الزمنية؛ يسجل الثواني بدل العدات ولا يحسب 1RM.': 'For planks and timed holds; logs seconds instead of reps, no 1RM.',
    'الوزن المرفوع:': 'Weight lifted:',
    'الوزن الفعلي المرفوع': 'Actual weight lifted',
    'كجم (kg)': 'kg',
    'باوند (lbs)': 'lb',
    '{0} كجم (kg)': '{0} kg',
    '{0} باوند (lbs)': '{0} lb',
    'المعادل:': 'Equals:',
    'وزن الجهاز (كجم، اختياري)': 'Machine weight (kg, optional)',
    'وزن الجهاز نفسه (كجم)': 'Machine weight itself (kg)',
    'اختياري. لو كتبته ينضاف للحجم و1RM في الجولات الجديدة، والجولات القديمة تبقى على حسابها إلا إذا طبقته عليها.': 'Optional. Adds to volume and 1RM for new sets; older sets keep their numbers unless you apply it to them.',
    'طبّق وزن الجهاز الحالي على جولاتي السابقة': 'Apply this machine weight to my past sets',
    'طبّق وزن الجهاز الحالي على جولاتي السابقة ({0})': 'Apply this machine weight to my past sets ({0})',
    'تطبيق وزن الجهاز على السجل': 'Apply machine weight to history',
    'طبّق': 'Apply',
    'تم تحديث {0} جولة': function (x) { return 'Updated ' + pl('set')(x); },
    'وزن البار (كجم) — للرسمة فقط': 'Bar weight (kg), for the drawing only',
    'وزن الجسم وقت الجولة (كجم)': 'Bodyweight at the time of the set (kg)',
    'وزن الجسم وقت التسجيل (كجم)': 'Bodyweight when logged (kg)',
    'وزن الجسم وقت الجولة': 'Bodyweight at the time of the set',
    'وزن الجسم وقت التسجيل': 'Bodyweight when logged',
    'المدة بالثواني:': 'Duration (seconds):',
    'المدة بالثواني': 'Duration (seconds)',
    'عدد العدات:': 'Reps:',
    'عدات': 'reps',
    'العدات': 'Reps',
    'مقياس الجهد الفعلي (RIR / العدات المتبقية للفشل):': 'Effort (RIR, reps left before failure):',
    'RIR (فارغ = غير محدد)': 'RIR (empty = not set)',
    'RIR 0 يعني أنك وصلت للفشل. نوع الجولة وRIR يظهران في السجل.': 'RIR 0 means you reached failure. Set type and RIR show in the log.',
    'RIR غير محدد': 'RIR not set',
    '0 (فشل)': '0 (failure)',
    '1 عدة': '1 rep',
    '2 عدة': '2 reps',
    '3 عدات': '3 reps',
    '4+ عدات': '4+ reps',
    'غير محدد': 'Not set',
    'نوع الجولة:': 'Set type:',
    'نوع الجولة': 'Set type',
    'عادية': 'Normal',
    'تسخين': 'Warm-up',
    'دروب': 'Drop',
    'سوبر': 'Superset',
    'فشل — تصنيف سابق': 'Failure (old label)',
    'فشل (سجل سابق)': 'Failure (old log)',
    'جولة العمل الأساسية بوزن وعدات تختارها. تُحسب ضمن جولات العمل.': 'A regular working set. Counts toward working sets.',
    'جولة خفيفة للتحضير. تبقى في السجل وتُستبعد من جولات العمل ومنحنى التطور.': 'A light prep set. Stays in the log but is left out of working sets and progress.',
    'تخفض الوزن بعد جولة وتكمل العدات. سجّل كل مرحلة وحدها، واختر «بدون مؤقت» بين المراحل.': 'Drop the weight after a set and keep going. Log each drop on its own and pick "No timer" between them.',
    'تمرينان متتاليان بدون راحة بينهما. سجّل كل تمرين وحده، واختر «بدون مؤقت» حتى تنتهي منهما.': 'Two exercises back to back with no rest. Log each one and pick "No timer" until both are done.',
    'تصنيف محفوظ من نسخة سابقة. استخدم RIR 0 عند تسجيل جولة جديدة وصلت فيها للفشل.': 'A label from an older version. Use RIR 0 for new sets taken to failure.',
    '1RM تقديري': 'Est. 1RM',
    'أقصى وزن (1RM):': 'Max (1RM):',
    '1RM حتى 15 عدة': '1RM up to 15 reps',
    'يظهر حتى 15 عدة': 'Shown up to 15 reps',
    '(دقة منخفضة)': '(low accuracy)',
    'غير مطبق للتمرين الزمني': 'Not for timed exercises',
    'ما ينطبق': 'N/A',
    'ما ينطبق على التمرين الزمني': 'N/A for timed exercises',
    'غير متاح': 'N/A',
    'حفظ الجولة': 'Save set',
    'كرر الجولة السابقة': 'Repeat last set',
    'كرر الجولة السابقة ·': 'Repeat last set ·',
    'تم حفظ الجولة ({0} كجم)': 'Set saved ({0} kg)',
    'تم حفظ الجولة ({0} باوند)': 'Set saved ({0} lb)',
    'تم حفظ {0} ثانية': 'Saved {0} s',
    'أدخل وزن جسمك في البروفايل أولًا لهذا النوع من التمارين': 'Add your bodyweight in the profile first for this type of exercise',
    'أدخل وزن الجسم وقت التسجيل لإعادة حساب السعرات بعد تغيير تفاصيل الكارديو': 'Enter the bodyweight at logging time to recalculate calories after changing cardio details',
    'اختر تمرينًا من نفس نوع التسجيل': 'Pick an exercise of the same log type',
    'رقم قياسي جديد في {0}': 'New record in {0}',

    /* ===== rest timer ===== */
    'مؤقت الراحة': 'Rest timer',
    'وقت الراحة التلقائي للجولة:': 'Auto rest after each set:',
    'بدون مؤقت (بين مراحل الدروب أو تمريني السوبر)': 'No timer (between drops or superset exercises)',
    '60 ثانية (تمارين العزل والتراي/الباي)': '60 s (isolation, triceps/biceps)',
    '90 ثانية (معياري)': '90 s (standard)',
    '120 ثانية (2 دقيقة - تمارين مركبة)': '120 s (2 min, compound lifts)',
    '180 ثانية (3 دقائق - سكوات / ديدليفت / بنش)': '180 s (3 min, squat / deadlift / bench)',
    'الراحة': 'Rest',
    'إيقاف الراحة': 'Stop rest',
    'إلغاء المؤقت': 'Cancel timer',
    'زد 15 ثانية': '+15 s',
    'نقص 15 ثانية': '−15 s',
    'زد 15 ثانية على الراحة': 'Add 15 seconds to the rest',
    'نقص 15 ثانية من الراحة': 'Take 15 seconds off the rest',
    'انتهت الراحة': 'Rest over',
    'انتهى وقت الراحة! حان وقت الجولة التالية': 'Rest is over! Time for the next set',
    'المؤقت يعمل؛ تعذر حفظه لإعادة فتح الصفحة': 'The timer is running but could not be saved for reopening the page',
    'المؤقتات': 'Timers',
    'الساعة': 'Clock',
    'الجلسة': 'Session',

    /* ===== today's log ===== */
    'سجل الجولات': 'Set log',
    'جولة واحدة': '1 set',
    '{0} جولات': pl('set'),
    '{0} جولة': pl('set'),
    '0 جولات': '0 sets',
    'اسحب الجولة يمين للتعديل، ويسار للحذف (وتقدر تتراجع 6 ثواني).': 'Swipe a set right to edit, left to delete (you can undo for 6 seconds).',
    'تعديل التسجيل': 'Edit entry',
    'حذف الجولة': 'Delete set',
    'حذف هذا التمرين المخصص': 'Delete this custom exercise',
    'تأكيد الحذف': 'Confirm delete',
    'هل أنت متاكد من حذف هذه الجولة؟': 'Delete this set?',
    'تم الحذف': 'Deleted',
    'انحذفت:': 'Deleted:',
    'تراجع': 'Undo',
    'رجعت الجولة': 'Set restored',
    'احذف': 'Delete',
    'مسح جولات اليوم': "Clear today's sets",
    'مسح اليوم': 'Clear today',
    'هل أنت متاكد من حذف جميع جولات وتسجيلات اليوم فقط؟': "Delete all of today's sets and entries?",
    'تم مسح جولات اليوم': "Today's sets cleared",
    'مسح سجلات جولات اليوم فقط': "Clear today's sets only",
    '{0} تقديري': '{0} kcal est.',
    'سعرات ضمن الجلسة': 'Counted in session',
    '{0} ثانية': '{0} s',
    '{0} دقيقة': '{0} min',
    '{0} كجم': '{0} kg',
    '{0} باوند': '{0} lb',
    '{0} يوم': pl('day'),
    '0 يوم': '0 days',
    'وزن الجسم × {0}': 'BW × {0}',
    'وزن الجسم': 'Bodyweight',
    'وزن الجسم ({0} كجم)': 'Bodyweight ({0} kg)',
    '(لكل يد)': '(per hand)',
    'لكل يد': 'per hand',
    'كجم لكل يد': 'kg per hand',
    'إضافي': 'added',
    'بمساعدة': 'assisted',
    'بالوقت': 'timed',
    'مساعدة': 'Assistance',
    'وزن إضافي': 'Added weight',
    'وزن إجمالي': 'Total weight',
    'مساعدة {0} كجم × {1}': 'Assist {0} kg × {1}',
    'مساعدة {0} باوند × {1}': 'Assist {0} lb × {1}',
    'تم تعديل التسجيل وتحديث ملخص الجلسة بدون تكرار': 'Entry updated and session summary refreshed',
    'حفظ التعديل': 'Save changes',
    'إلغاء': 'Cancel',
    'تأكيد': 'Confirm',
    'إغلاق': 'Close',
    'تم': 'Done',
    'فهمت': 'Got it',
    'تعذر إتمام العملية': 'Could not complete that',
    'التمرين (من نفس نوع التسجيل)': 'Exercise (same log type)',
    'الوزن المسجل': 'Logged weight',
    'الوزن المسجل (': 'Logged weight (',
    'للسجلات القديمة: يمكنك تعديل المدة فقط دون وزن الجسم. أدخل الوزن التاريخي عند تغيير السرعة أو الشدة لإعادة الحساب.': 'For older entries you can change only the duration without bodyweight. Enter the bodyweight from that time if you change speed or intensity.',

    /* ===== cardio ===== */
    'كارديو': 'Cardio',
    'كارديو بالجهاز': 'Cardio machine',
    'جهاز مشي': 'Treadmill',
    'دراجة ثابتة': 'Stationary bike',
    'دراجة هوائية': 'Bike',
    'إليبتيكال': 'Elliptical',
    'تجديف': 'Rower',
    'درج': 'Stair climber',
    'نوع الجهاز': 'Machine',
    'الجهاز': 'Machine',
    'طريقة الحركة:': 'Movement:',
    'الحركة': 'Movement',
    'مشي': 'Walk',
    'جري': 'Run',
    'السرعة (كم/س):': 'Speed (km/h):',
    'السرعة (كم/س)': 'Speed (km/h)',
    'السرعة كم/س': 'Speed km/h',
    'السرعة': 'Speed',
    'السرعة/الشدة': 'Speed / intensity',
    'الارتفاع (Incline):': 'Incline:',
    'الميل %': 'Incline %',
    'الميل': 'Incline',
    'المدة (بالدقائق):': 'Duration (minutes):',
    'المدة بالدقائق': 'Duration (minutes)',
    'المدة': 'Duration',
    'الشدة الفعلية:': 'Intensity:',
    'الشدة': 'Intensity',
    'خفيفة': 'Light',
    'متوسطة': 'Moderate',
    'عالية': 'High',
    'شدة خفيفة': 'Light intensity',
    'شدة متوسطة': 'Moderate intensity',
    'شدة عالية': 'High intensity',
    'شدة غير محددة': 'Intensity not set',
    'متوسط الواط (اختياري — يُستخدم حسابيًا للدراجة الثابتة فقط):': 'Average watts (optional, used for the stationary bike only):',
    'الواط (اختياري للدراجة الثابتة)': 'Watts (optional, stationary bike)',
    'الواط': 'Watts',
    'الحساب يميز بين الدراجة والغزالة والتجديف والسلالم، ولا يعتمد رقم Level غير القابل للمقارنة بين الأجهزة.': 'Calories differ for bike, elliptical, rower and stairs. The machine "Level" number is ignored because it is not comparable between machines.',
    'حفظ تمرين الكارديو': 'Save cardio',
    'تم حفظ تمرين الكارديو': 'Cardio saved',
    '{0} · {1} كم/س · ميل {2}%': '{0} · {1} km/h · incline {2}%',
    'جري · {0} كم/س · ميل {1}%': 'Run · {0} km/h · incline {1}%',
    'مشي · {0} كم/س · ميل {1}%': 'Walk · {0} km/h · incline {1}%',

    /* ===== visuals over the weight ===== */
    'رسمة البار': 'Barbell drawing',
    'رسمة دمبلين': 'Dumbbells drawing',
    'رسمة جهاز بأقراص': 'Plate-loaded machine drawing',
    'رسمة عمود أوزان الجهاز': 'Weight stack drawing',
    'رسمة وزن الجسم': 'Bodyweight drawing',
    'شاشة جهاز المشي': 'Treadmill display',
    'شاشة جهاز الكارديو': 'Cardio machine display',
    'نفس شاشة الجهاز': 'Same as the machine display',
    'بدل الوزن: المدة بالثواني': 'Instead of weight: duration in seconds',
    'أدخل وزن جسمك في البروفايل': 'Add your bodyweight in the profile',
    'البار فاضي ({0})': 'Empty bar ({0})',
    'أقل من وزن البار ({0})': 'Less than the bar ({0})',
    '· وزن الجهاز ما انحسب': '· machine weight not counted',
    'وزن جسمك {0}': 'Your bodyweight {0}',
    'أكبر قرص': 'Largest plate',

    /* ===== add exercise screen ===== */
    'إضافة تمرين مخصص جديد': 'Add a custom exercise',
    'اسم التمرين المخصص:': 'Exercise name:',
    'مثال: Incline Dumbbell Press أو hip adduction': 'e.g. Incline Dumbbell Press or hip adduction',
    'اكتب اسم التمرين ويقترح التطبيق تصنيفه؛ راجع الفئة والأداة قبل الحفظ': 'Type the name and the app suggests a category; check category and equipment before saving',
    'الفئة التدريبية:': 'Category:',
    'نوع الجهاز/الأداة:': 'Equipment:',
    'نوع الجهاز للتمرين المخصص إذا كان كارديو:': 'Cardio machine type (if cardio):',
    'حفظ التمرين المخصص': 'Save custom exercise',
    'حفظ التمرين': 'Save exercise',
    'التمارين المخصصة التي أضفتها': 'Your custom exercises',
    'لم تقم بإضافة أي تمارين مخصصة بعد. قم بإضافة تمارينك الخاصة أعلاه!': "You haven't added any custom exercises yet. Add your own above!",
    'تمت إضافة التمرين المخصص بنجاح!': 'Custom exercise added!',
    'تم تصنيف التمرين تلقائياً بنجاح': 'Exercise categorized automatically',
    'هذا التمرين مضاف مسبقاً في المكتبة!': 'This exercise is already in the library!',
    'التمرين موجود مسبقًا': 'Exercise already exists',
    'يرجى إدخال اسم التمرين أولاً': 'Enter the exercise name first',
    'حذف تمرين مخصص': 'Delete custom exercise',
    'هل أنت متاكد من حذف هذا التمرين المخصص؟ لن يتم حذف الجولات القديمة المسجلة به.': 'Delete this custom exercise? Sets already logged with it are kept.',
    'تم حذف التمرين المخصص': 'Custom exercise deleted',
    'الفئة: {0} | الأداة: {1}': 'Category: {0} | Equipment: {1}',
    'مخصص': 'Custom',
    'دفع (Push)': 'Push',
    'سحب (Pull)': 'Pull',
    'أرجل (Legs)': 'Legs',
    'دفع': 'Push',
    'سحب': 'Pull',
    'أرجل': 'Legs',
    'صدر': 'Chest',
    'ظهر': 'Back',
    'أكتاف': 'Shoulders',
    'ذراع': 'Arms', 'باي': 'Biceps', 'تراي': 'Triceps',
    'بطن': 'Core',
    'أجهزة': 'Machines',
    'بار': 'Barbell',
    'دمبل': 'Dumbbell',
    'أوزان حرة': 'Free weights',
    'أوزان حرة (بار)': 'Free weights (barbell)',
    'أوزان حرة (دمبل)': 'Free weights (dumbbell)',
    'كابل / وزن الجسم': 'Cable / bodyweight',
    'كابل / وزن جسم': 'Cable / bodyweight',
    'كابل/وزن جسم': 'Cable/bodyweight',
    'بأقراص تركّبها بنفسك': 'Plate-loaded',
    'بدبوس (عمود أوزان)': 'Pin-loaded (weight stack)',
    'جهاز T-Bar Row': 'T-Bar Row Machine',
    'تمرين': 'Exercise',
    'جولة': 'Set',
    'جولات': 'sets',
    'جولة تمرين': 'Workout set',

    /* ===== progress ===== */
    'تطور الأداء': 'Performance progress',
    'أقسام التطور': 'Progress sections',
    'الأرقام القياسية': 'Records',
    'أرقامك القياسية': 'Your records',
    'أعلى حمل وأعلى 1RM تقديري لكل تمرين (بدون التسخين). اضغط على تمرين عشان تشوف رسمه.': 'Heaviest load and best est. 1RM per exercise (warm-ups excluded). Tap an exercise to see its chart.',
    'سجّل جولات وبتطلع أرقامك هنا.': 'Log some sets and your records show up here.',
    'أعلى حمل': 'Top load',
    'أعلى حمل مسجل': 'Top load logged',
    'أعلى 1RM تقديري': 'Best est. 1RM',
    'أطول مدة': 'Longest',
    'الالتزام': 'Consistency',
    'الشهر السابق': 'Previous month',
    'الشهر الجاي': 'Next month',
    'أيام هالشهر': 'Days this month',
    'أيام هالأسبوع': 'Days this week',
    'أسابيع متتالية': 'Weeks in a row',
    'الأسبوع يبدأ الأحد. الأسبوع الحالي ما يكسر السلسلة لو ما تمرنت فيه لسه. اضغط على يوم تمرنت فيه عشان تشوف جولاته.': "Weeks start on Sunday. This week doesn't break the streak if you haven't trained yet. Tap a training day to see its sets.",
    'تمرنت يوم': 'Trained on',
    'لا توجد جولات مسجلة في هذا التاريخ.': 'No sets logged on this date.',
    'العضلات هالأسبوع': 'Muscles this week',
    'الجولات هالأسبوع لكل عضلة': 'Sets per muscle this week',
    'جولات العمل بدون التسخين. التمرين المركب ينحسب لعضلته الأساسية بس (البنش للصدر). الخط الرمادي = الأسبوع الماضي.': 'Working sets without warm-ups. Compound lifts count for their main muscle only (bench for chest). Grey line = last week.',
    'الأسبوع الماضي:': 'Last week:',
    '{0}: {1} جولة هالأسبوع، {2} الأسبوع الماضي': '{0}: {1} sets this week, {2} last week',
    'سجل الجلسات': 'Session history',
    'لما تنهي أول جلسة بتطلع هنا.': 'Your first finished session shows up here.',
    'عرض جلسات أقدم': 'Show older sessions',
    'وزنك وخصرك مع الوقت': 'Weight and waist over time',
    'من سجل القياسات اللي تحفظه هنا (قياس واحد لكل يوم).': 'From the measurements you save here (one per day).',
    'احفظ وزنك (ومحيط خصرك لو تبي) من فوق، وكل يوم تحفظ فيه يصير نقطة في الرسم.': 'Save your weight (and waist if you like) above; each day you save becomes a point on the chart.',
    'قياس واحد': 'One measurement',
    'أعمدة التطور': 'Progress bars',
    'منحنى تطور التمرين المختار': 'Progress chart for the selected exercise',
    'اختر تمرين للعرض': 'Pick an exercise',
    'قارن الجولات بنفس طريقة تسجيل الحمل:': 'Compare sets with the same load type:',
    'الوزن الفعلي المرفوع ': 'Actual weight lifted',
    'أقصى قوة نظرية (1RM)': 'Theoretical max (1RM)',
    'سجل تطور أوزان التمرين (جلسة بجلسة)': 'Weight history (session by session)',
    'عرض باقي الجولات': 'Show remaining sets',
    'عرض الكل': 'Show all',
    'لا توجد بيانات مناسبة للرسم': 'Not enough data for a chart',
    'لا توجد جولات عمل بهذه الطريقة': 'No working sets with this load type',
    'لا توجد جولات عمل مسجلة': 'No working sets logged',
    'لا توجد تمارين بها سجلات بعد': 'No exercises with logs yet',
    'الحجم التدريبي الإجمالي لكُل تمرين (Volume)': 'Total volume per exercise',
    'بالأطنان': 'in tonnes',
    'لا توجد سجلات أوزان لحساب الحجم حتى الآن': 'No weight logs to calculate volume yet',
    'فعلي: {0} طن': 'Working: {0} t',
    'الإجمالي مع التسخين: {0} طن': 'With warm-ups: {0} t',
    'طن': 't',
    'عدد التمارين النشطة': 'Active exercises',
    'إجمالي أيام التمرين': 'Total training days',
    'تاريخ سجل الجولات': 'Set history',
    '{0} {1} (السابق {2})': '{0} {1} (previous {2})',
    '{0} ثانية (السابق {1})': '{0} s (previous {1})',
    '1RM {0} كجم (السابق {1})': '1RM {0} kg (previous {1})',
    '1RM {0} باوند (السابق {1})': '1RM {0} lb (previous {1})',
    '{0} كجم (السابق {1})': '{0} kg (previous {1})',
    '{0} باوند (السابق {1})': '{0} lb (previous {1})',

    /* ===== analysis (bento) ===== */
    'تحليل القياسات والسعرات التقديرية': 'Body measurements and calorie estimates',
    'تحليل رياضي تقريبي يعتمد على مدخلات بروفايلك، وليس تشخيصًا طبيًا': 'A rough estimate from your profile, not a medical diagnosis',
    'يرجى الانتقال لصفحة "البروفايل" وإدخال الطول والوزن لظهور التحليل الذكي': 'Go to the Profile and enter your height and weight to see the analysis',
    'أهداف السعرات اليومية المطلوبة': 'Daily calorie targets',
    'تثبيت الوزن (Maintenance)': 'Maintenance',
    'هدف التوازن': 'Stay even',
    'تقدير يومي للمحافظة على الوزن، ويُراجع حسب تغير وزنك الفعلي.': 'Daily estimate to keep your weight; adjust it to how your weight actually changes.',
    'نقصان الوزن (Fat Loss)': 'Fat loss',
    'عجز {0}–{1}%': '{0}–{1}% deficit',
    'نطاق مبدئي للتنشيف يُعدّل حسب تغير الوزن والأداء، دون ضمان تلقائي لمنع فقدان العضلات.': 'A starting range for a cut; adjust it to your weight and performance. It does not guarantee you keep muscle.',
    'زيادة نظيفة (Lean Bulk)': 'Lean bulk',
    'فائض {0}–{1}%': '{0}–{1}% surplus',
    'فائض محافظ كبداية، ثم يُعدّل حسب معدل زيادة الوزن.': 'A careful surplus to start, then adjust to how fast your weight goes up.',
    'مؤشرات تناسب الوزن والخصر': 'Weight and waist ratios',
    'مؤشر الكتلة (BMI)': 'Body mass index (BMI)',
    'أداة فرز عامة لا تميز بين العضلات والدهون، وقد تضلل لدى لاعبي الحديد.': "A general screening tool; it can't tell muscle from fat and can mislead lifters.",
    'نسبة الخصر للطول (WHtR)': 'Waist-to-height ratio (WHtR)',
    'مؤشر بسيط مرتبط بالسمنة المركزية، وليس قياسًا مباشرًا للدهون الحشوية.': 'A simple marker of central fat, not a direct measure of visceral fat.',
    'مؤشر الكتلة الخالية من الدهون (FFMI)': 'Fat-free mass index (FFMI)',
    'يشمل الكتلة الخالية من الدهون كلها، وليس العضلات وحدها.': 'Includes all fat-free mass, not just muscle.',
    'مؤشرات تركيب الجسم والعضلات': 'Body composition',
    'نسبة الدهون': 'Body fat',
    'نسبة الدهون %': 'Body fat %',
    'نسبة الدهون الكلية.': 'Total body fat.',
    'شحوم الجسم': 'Body fat',
    'نسبة العضلات': 'Muscle',
    'نسبة الأنسجة العضلية.': 'Share of muscle tissue.',
    'أنسجة عضلية': 'Muscle tissue',
    'نسبة السوائل': 'Body water',
    'نسبة السوائل الترطيبية.': 'Share of body water.',
    'ترطيب الخلايا': 'Hydration',
    'ضمن النطاق الطبيعي': 'Within the normal range',
    'أعلى من النطاق الطبيعي': 'Above the normal range',
    'أقل من النطاق الطبيعي': 'Below the normal range',
    'مرتفع حسب BMI': 'High by BMI',
    'مرتفع كأداة فرز': 'High as a screening flag',
    'يستحق المتابعة': 'Worth watching',
    'غير مناسب لهذا النطاق': 'Not suited to this range',
    'أقل من 0.5': 'Under 0.5',
    'سعرة': 'kcal',

    /* ===== profile ===== */
    'شكل التطبيق': 'App look',
    'سياسة الخصوصية': 'Privacy policy',
    'الأقراص': 'Plates',
    'أسود وأحمر، أرقام كبيرة ورسمة الأقراص': 'Black and red, big numbers and the plate drawing',
    'الدفتر': 'Logbook',
    'فاتح ومرتب، جولاتك صفوف مثل الدفتر الورقي': 'Light and tidy, your sets in rows like a paper logbook',
    'أسود مثل ساعة الجيم، مؤقتات LED وأزرار ضخمة': 'Black like a gym clock, LED timers and huge buttons',
    'تلقائي': 'Auto',
    'الدفتر لما يكون جوالك فاتح، والأقراص لما يكون غامق': 'Logbook when your phone is in light mode, Plates in dark mode',
    'أثناء الجلسة': 'During the session',
    'خلّ الشاشة شغالة': 'Keep the screen on',
    'ما تنطفي بين الجولات، وترجع طبيعية لما تنهي الجلسة': 'Stays on between sets and goes back to normal when you finish',
    'اهتزاز خفيف مع الأزرار': 'Light vibration on taps',
    'لما تحفظ جولة أو تضغط + و −، ولما تخلص الراحة': 'When you save a set, tap + or −, and when rest ends',
    'الشاشة بتبقى شغالة أثناء الجلسة': 'The screen will stay on during sessions',
    'الشاشة تنطفي عادي': 'The screen turns off as usual',
    'الاهتزاز شغال': 'Vibration on',
    'الاهتزاز مطفي': 'Vibration off',
    'هل أنت رجل؟': 'Are you male?',
    'مفعل: خيار الرجل': 'On: male',
    'مفعل: خيار الأنثى': 'On: female',
    'تم اختيار وضع الرجل': 'Male selected',
    'تم اختيار وضع الأنثى': 'Female selected',
    'البيانات الشخصية والقياسات': 'Personal details and measurements',
    'الاسم الأول:': 'First name:',
    'مثال: أحمد': 'e.g. Alex',
    'العمر:': 'Age:',
    'العمر': 'Age',
    'الطول (سم):': 'Height (cm):',
    'الطول': 'Height',
    'الوزن (كجم):': 'Weight (kg):',
    'الوزن': 'Weight',
    'محيط الخصر (سم):': 'Waist (cm):',
    'محيط الخصر': 'Waist',
    'مثال: 25': 'e.g. 25',
    'مثال: 175': 'e.g. 175',
    'مثال: 75': 'e.g. 75',
    'مثال: 80': 'e.g. 80',
    'مثال: 140': 'e.g. 140',
    'مستوى النشاط اليومي:': 'Daily activity level:',
    'مستوى النشاط': 'Activity level',
    'قليل الحركة': 'Sedentary',
    'نشاط خفيف — 1 إلى 3 أيام': 'Light (1–3 days a week)',
    'نشاط متوسط — 3 إلى 5 أيام': 'Moderate (3–5 days a week)',
    'نشاط عالٍ — 6 إلى 7 أيام': 'High (6–7 days a week)',
    'نشاط عالٍ جدًا / عمل بدني': 'Very high / physical job',
    'نسب الجسم المتقدمة (اختياري):': 'Advanced body composition (optional):',
    'الدهون %:': 'Fat %:',
    'العضلات %:': 'Muscle %:',
    'العضلات %': 'Muscle %',
    'السوائل %:': 'Water %:',
    'السوائل %': 'Water %',
    'حفظ القياسات وتحليل النتائج': 'Save and analyze',
    'تم حفظ القياسات والبروفايل بنجاح': 'Profile and measurements saved',
    'سجل تغيرات الوزن والقياسات': 'Weight and measurement history',
    'لا توجد قياسات سابقة مسجلة': 'No measurements yet',
    'خصر: {0} سم': 'Waist: {0} cm',
    'سم': 'cm',
    'إدارة البيانات وقواعد البيانات IndexedDB': 'Data and storage',
    'تصدير JSON': 'Export JSON',
    'استيراد JSON': 'Import JSON',
    'تنزيل نسخة الأمان قبل التحديث': 'Download the pre-update safety copy',
    'مسح جميع بيانات التطبيق': 'Erase all app data',
    'إعادة ضبط شاملة': 'Full reset',
    'مسح شامل لكل شيء': 'Erase everything',
    'مسح الكل': 'Erase all',
    'تحذير: سيتم حذف جميع البيانات الشخصية والسجلات والمكتبة ونسخ الأمان المحلية نهائياً وإعادة التطبيق للوضع الافتراضي.': 'Warning: this permanently deletes your profile, logs, library and local safety copies, and resets the app.',
    'تمت إعادة ضبط التطبيق بالكامل': 'The app has been reset',
    'لا توجد نسخة أمان سابقة على هذا الجهاز': 'No safety copy on this device',
    'تم فحص النسخة الاحتياطية وتجهيزها للتنزيل': 'Backup checked and ready to download',
    'تم تجهيز النسخة مع تنبيه': 'Backup ready, with a warning',
    'احتفظ بالنسخة. يلزم تصحيح سجل قديم قبل إعادة استيرادها:': 'Keep this backup. An old entry needs fixing before it can be imported again:',
    'تم دمج النسخة والتحقق منها وحفظها بنجاح': 'Backup merged, checked and saved',
    'الملف كبير جدًا؛ الحد 25 ميجابايت': 'The file is too big; the limit is 25 MB',
    'الملف مو نسخة احتياطية من التطبيق، أو تالف. اختر ملف .json صدّرته من Gym Tracker.': "This file isn't a Gym Tracker backup, or it's damaged. Pick a .json file you exported from Gym Tracker.",
    'ملفات الموقع غير متوافقة. ارفع index.html مع باقي ملفات التحديث ثم أغلق التطبيق وافتحه. سجلك محفوظ.': "The site files don't match. Upload index.html with the other update files, then close and reopen the app. Your log is safe.",
    'عن الأرقام التقديرية وحفظ البيانات': 'About estimates and your data',
    'السعرات و1RM ومؤشرات الجسم تقديرات إرشادية. 1RM يظهر حتى 15 عدة فقط. البيانات محفوظة على هذا الجهاز؛ صدّر نسخة JSON للاحتفاظ بها خارج المتصفح.': 'Calories, 1RM and body figures are estimates. 1RM shows for up to 15 reps. Your data is stored on this device; export a JSON copy to keep it elsewhere.',
    'أغلق النسخة القديمة المفتوحة ليكتمل تحديث التخزين': 'Close the older open copy to finish updating storage',
    'تعذر إتمام المسح الشامل. لم يُعتمد المسح.': 'The full erase could not finish. Nothing was erased.',
    'تعذر إنشاء نسخة أمان قبل التحديث. صدّر بياناتك من النسخة السابقة أولًا.': 'Could not create a safety copy before updating. Export your data from the previous version first.',
    'تغيرت البيانات في نافذة أخرى. أعد تحميل الصفحة قبل الحفظ.': 'Your data changed in another window. Reload the page before saving.',
    'حُذفت البيانات الرئيسية، لكن تعذر حذف إحدى النسخ المحلية. امسح بيانات الموقع لإكمال الحذف.': "The main data was deleted, but a local copy couldn't be. Clear the site data to finish.",
    'لم يتم الحفظ: التخزين المحلي غير متاح أو ممتلئ.': 'Not saved: local storage is unavailable or full.',
    'لم يتم الحفظ: تعذر التخزين على الجهاز. احتفظ بالصفحة مفتوحة وصدّر نسخة من بياناتك.': 'Not saved: storage on this device failed. Keep the page open and export a copy of your data.',

    /* ===== import validation (data.js) ===== */
    'ملف غير صالح:': 'Invalid file:',
    'لا توجد بيانات تطبيق': 'no app data',
    'إصدار أحدث غير مدعوم': 'newer version not supported',
    'جولة مرتبطة بجلسة مفقودة': 'a set points to a missing session',
    'توجد جلستان نشطتان؛ أنهِ الجلسة الحالية أو استورد نسخة بجلسات مكتملة': 'two active sessions; finish the current one or import a backup with finished sessions',
    'وزن الجسم عند تسجيل الجولة مفقود': 'bodyweight at the time of the set is missing',
    'وزن الجسم عند تسجيل الجولة غير صالح': 'bodyweight at the time of the set is invalid',
    'العدات يجب أن تكون عددًا صحيحًا': 'reps must be a whole number',
    'معرف السجل': 'record id', 'التاريخ': 'date', 'الاسم': 'name', 'الجنس': 'sex', 'الثيم': 'theme', 'اللغة': 'Language',
    'الإعدادات': 'settings', 'وقت البروفايل': 'profile time', 'القياسات': 'measurements', 'قياس': 'measurement',
    'الخصر': 'waist', 'اسم التمرين': 'exercise name', 'الفئة': 'category', 'نوع التمرين': 'exercise type',
    'الأداة': 'equipment', 'الوحدة': 'unit', 'طريقة الحمل': 'load type', 'الوزن المعروض': 'shown weight',
    'الثواني': 'seconds', 'وزن الجهاز': 'Machine weight', 'السعرات': 'calories', 'مدة الكارديو': 'cardio duration',
    'نوع الحركة': 'movement', 'جلسة': 'Session', 'اسم الجلسة': 'session name', 'الروتين': 'routine',
    'بداية الجلسة': 'session start', 'نهاية الجلسة': 'session end', 'حالة الجلسة': 'session status',
    'وزن الجلسة': 'session bodyweight', 'تمارين الجلسة': 'session exercises', 'الملف': 'file',

    /* ===== months, days, short units ===== */
    'يناير': 'January', 'فبراير': 'February', 'مارس': 'March', 'أبريل': 'April', 'مايو': 'May', 'يونيو': 'June',
    'يوليو': 'July', 'أغسطس': 'August', 'سبتمبر': 'September', 'أكتوبر': 'October', 'نوفمبر': 'November', 'ديسمبر': 'December',
    'الأحد': 'Sunday', 'الاثنين': 'Monday', 'الثلاثاء': 'Tuesday', 'الأربعاء': 'Wednesday', 'الخميس': 'Thursday', 'الجمعة': 'Friday', 'السبت': 'Saturday',
    'ح': 'S', 'ن': 'M', 'ث': 'T', 'ر': 'W', 'خ': 'T', 'ج': 'F', 'س': 'S',
    'كجم': 'kg', 'باوند': 'lb', 'ثانية': 's', 'ثوانٍ': 's', 'دقيقة': 'min', 'د': 'min', 'يوم': 'day',
    '{0}ث': '{0}s', '{0}د': '{0}m', '{0} د': '{0} min', '{0}كم': '{0}km',
    'البداية': 'Start', 'النوع': 'Type', 'نتيجة': 'Result',
    '0 = ما ينحسب': '0 = not counted',
    'الرجوع للتمرين': 'Back to workout',
    'حذف التسجيل': 'Delete entry',
    'نظام الجدول:': 'Split:',
    'الأسبوع الماضي': 'Last week',
    'وزن الجهاز ما انحسب': 'machine weight not counted',
    '{0} سعرة': '{0} kcal',
    '{0} كجم لكل يد': '{0} kg per hand',
    '{0} باوند لكل يد': '{0} lb per hand',
    'كجم لكل يد': 'kg per hand',
    'باوند لكل يد': 'lb per hand',
    '{0} كجم إضافي': '{0} kg added',
    '{0} باوند إضافي': '{0} lb added',
    '{0} كجم مساعدة': '{0} kg assist',
    '{0} باوند مساعدة': '{0} lb assist',
    '{0} عدات': pl('rep'),
    '{0} عدة': pl('rep'),
    '{0} من {1}': '{0} since {1}',
    '{0} (الرسمة بخطوة {1})': '{0} (drawn in steps of {1})',
    '[1RM: {0} كجم (دقة منخفضة)]': '[1RM: {0} kg (low accuracy)]',
    '[1RM: {0} باوند (دقة منخفضة)]': '[1RM: {0} lb (low accuracy)]',
    '[1RM: {0} كجم]': '[1RM: {0} kg]',
    '[1RM: {0} باوند]': '[1RM: {0} lb]',
    'زد 5 ثواني.': 'Add 5 seconds.',
    'كان باقي فيك كثير، زد 10 ثواني.': 'You had plenty left, add 10 seconds.',
    'وRIR {0}': '· RIR {0}',
    '66.7 كجم': '66.7 kg', '110.2 باوند': '110.2 lb'
  }, [
    // sentences that carry a name or a word that changes (exercise, unit, session name)
    [/^رقم قياسي جديد في (.+?): (.+)$/, function (a, b) { return 'New record in ' + t(a) + ': ' + t(b); }],
    [/^بدأت (.+)$/, function (a) { return 'Started ' + t(a); }],
    [/^ملخص (.+)$/, function (a) { return t(a) + ' summary'; }],
    [/^بيتغير حساب ([\d.,]+) جولة سابقة لـ "(.+)" عشان تنحسب بوزن جهاز ([\d.,]+) كجم \(الأقراص اللي سجلتها ما تتغير\)\. تقدر ترجعها بكتابة صفر وتطبيقه مرة ثانية\.$/,
      function (c, name, kg) { return pl('past set')(c) + ' of "' + t(name) + '" will be recalculated with a ' + kg + ' kg machine weight (the plates you logged stay the same). To undo, enter zero and apply again.'; }],
    [/^المدة: (.+?) دقيقة \| الجولات الفعلية: (.+?) \| الحجم الفعلي: (.+?) طن \| متوسط RIR: (.+?) \| أعلى 1RM مسجل بين التمارين: (.+?) \| السعرات التقديرية للحديد والكارديو: (.+)$/,
      function (d, s, v, r, o, c) { return 'Duration: ' + d + ' min | Working sets: ' + s + ' | Working volume: ' + v + ' t | Average RIR: ' + t(r) + ' | Best 1RM: ' + t(o) + ' | Estimated calories (weights and cardio): ' + t(c); }],
    [/^آخر جلسة \((.+?)\): (.+?) × ([\d.,]+)(?: وRIR (\S+)| (بدون) RIR)\.(?: (.*))?$/, function (d, w, r, rir, none, rest) {
      return 'Last session (' + t(d) + '): ' + t(w) + ' × ' + r + (none ? ', no RIR' : ' at RIR ' + rir) + '.' + (rest ? ' ' + t(rest) : ''); }],
    [/^آخر مرة ([\d.,]+) ثانية(?: وRIR (\S+))?\.(?: (.*))?$/, function (s, rir, rest) { return 'Last time ' + s + ' s' + (rir ? ' at RIR ' + rir : '') + '.' + (rest ? ' ' + t(rest) : ''); }],
    [/^باقي فيك (عدة|عدتين): ثبّت الوزن وزد عدة\.$/, function (a) { return (a === 'عدة' ? 'You had 1 rep left' : 'You had 2 reps left') + ': keep the weight and add a rep.'; }],
    [/^وصلت ([\d.,]+) عدة( وفيك عدات باقية)?\. زد (.+?) وارجع ([\d.,]+) عدات وابنِ عليها\.$/, function (r, left, a, b) { return 'You reached ' + r + ' reps' + (left ? ' with reps to spare' : '') + '. Add ' + t(a) + ', drop back to ' + b + ' reps and build up again.'; }],
    [/^تمرنت يوم (.+)$/, function (d) { return 'Trained on ' + t(d); }],
    [/^(.+?): ([\d.,]+) جولة هالأسبوع، ([\d.,]+) الأسبوع الماضي$/, function (m, a, b) { return t(m) + ': ' + a + ' sets this week, ' + b + ' last week'; }],
    [/^· (.+)$/, function (a) { return '· ' + t(a); }],
    // "Name (فئة)" or "label (unit)": translate both parts
    [/^(.+?) \(([^()]*[\u0600-\u06FF][^()]*)\)$/, function (a, b) { var x = t(a), y = t(b); return x + ' (' + y + ')'; }],
    // label followed by a unit word: "أعلى حمل مسجل كجم لكل يد"
    [/^(.*[\u0600-\u06FF].*?) (كجم لكل يد|باوند لكل يد|كجم|باوند|ثانية)$/, function (a, u) { return t(a) + ' (' + t(u) + ')'; }],
    [/^كان باقي فيك 3 عدات أو أكثر، يعني الوزن صار خفيف عليك\. زد (.+?) وخلك على ([\d.,]+) عدات\.$/, function (a, r) { return 'You had 3+ reps left, so the weight is getting light. Add ' + t(a) + ' and stay at ' + r + ' reps.'; }],
    [/^خفف المساعدة (.+?) (.+?) — المساعدة الأقل يعني حمل أكبر عليك\.$/, function (a, u) { return 'Lower the assistance by ' + a + ' ' + t(u) + '; less assistance means more load on you.'; }],
    [/^(.+?) يجب أن يكون بين (.+?) و(.+)$/, function (l, a, b) { return t(l) + ' must be between ' + a + ' and ' + b; }],
    [/^(.+?) يجب أن يكون عددًا صحيحًا$/, function (l) { return t(l) + ' must be a whole number'; }],
    [/^أدخل (.+)$/, function (l) { return 'Enter ' + t(l).toLowerCase(); }],
    [/^(.*) \((.+?)، السجل ([\d]+)\)$/, function (m, key, i) { return t(m) + ' (' + key + ', entry ' + i + ')'; }],
    [/^معرفات مكررة في (.+)$/, function (k) { return 'Duplicate ids in ' + k; }],
    [/^الدبوس على (.+)$/, function (a) { return 'Pin at ' + t(a); }],
    [/^كل جهة: (.+)$/, function (a) { return 'Each side: ' + t(a); }],
    [/^وزنك (.+?) \+ (.+?) = (.+)$/, function (a, b, c) { return 'You ' + a + ' + ' + b + ' = ' + c; }],
    [/^وزنك (.+?) − مساعدة (.+?) = (.+)$/, function (a, b, c) { return 'You ' + a + ' − assist ' + b + ' = ' + c; }],
    [/^(.+?) لكل يد · الحجم يحسب اليدين \(×2\)$/, function (a) { return a + ' per hand · volume counts both hands (×2)'; }],
    [/^· \+ الجهاز (.+)$/, function (a) { return '· + machine ' + a; }],
    [/^(.+?) · البار (.+)$/, function (a, b) { return t(a) + ' · bar ' + b; }],
  ]);

  /* ---------- v11.3 (batch 1) ---------- */
  GymI18n.add({
    'الجهاز مشغول؟': 'Machine taken?',
    'مثال: الكرسي على 4، قبضة واسعة': 'e.g. seat on 4, wide grip',
    'ملاحظة التمرين': 'Exercise note',
    'حفظ': 'Save',
    'تسخين:': 'Warm-up:',
    'كيف كانت الجولة؟': 'How did the set feel?',
    'سهل': 'Easy', 'مناسب': 'Right', 'صعب': 'Hard',
    'كان فيني {0} عدات أو أكثر': '{0}+ reps left',
    'باقي فيني عدة أو عدتين': '1 or 2 reps left',
    'وصلت للحد': 'Hit my limit',
    'يتذكر الراحة اللي تختارها لكل تمرين.': 'Remembers the rest you pick for each exercise.',
    'قيّم الجولة بسهل / مناسب / صعب': 'Rate sets as Easy / Right / Hard',
    'ثلاث أزرار بدل أرقام RIR، والتطبيق يحوّلها لـ RIR من ورا': 'Three buttons instead of RIR numbers; the app turns them into RIR for you',
    'تصدير Excel (CSV)': 'Export for Excel (CSV)',
    'بديل لنفس العضلة': 'Swap for the same muscle',
    'ملاحظتك:': 'Your note:',
    '+ أضف ملاحظة لهالتمرين': '+ Add a note for this exercise',
    'انحفظت الملاحظة': 'Note saved',
    'انمسحت الملاحظة': 'Note removed',
    'تعبّت جولة التسخين. احفظها بعد ما تسويها': 'Warm-up set filled in. Save it after you do it',
    'آخر مرة': 'Last time',
    'ما سجلته قبل': 'Not logged yet',
    'التمرين غير موجود': 'Exercise not found',
    'ما فيه جولات تتصدّر للحين': 'No sets to export yet',
    'تم تجهيز ملف Excel ({0} صف)': function (x) { return 'Excel file ready (' + x + (n(x) === 1 ? ' row)' : ' rows)'); },
    'صرت تقيّم الجولة بسهل / مناسب / صعب': 'Sets are now rated Easy / Right / Hard',
    'رجعت أرقام RIR': 'Back to RIR numbers',
    'طريقة تقييم الجولة': 'Set rating mode'
  }, [
    [/^بدائل (.+) لنفس العضلة\. اللي سويتها قبل فوق\.$/, function (a) { return 'Alternatives to ' + t(a) + ' for the same muscle. The ones you have done come first.'; }],
    [/^بدّلت (.+) بـ (.+) لهالجلسة$/, function (a, b) { return 'Swapped ' + t(a) + ' for ' + t(b) + ' in this session'; }],
    [/^انتقلت لـ (.+)$/, function (a) { return 'Switched to ' + t(a); }],
    [/^كسرت رقمك في (.+) و([\d]+) غيرها\.$/, function (a, k) { return 'New records in ' + a.split('، ').map(t).join(', ') + ' and ' + k + ' more.'; }],
    [/^كسرت رقمك في (.+)\.$/, function (a) { var p = a.split('، '); return (p.length > 1 ? 'New records in ' : 'New record in ') + p.map(t).join(', ') + '.'; }],
    [/^متأخر في (.+?): ([\d.,]+) جولات هالأسبوع، و([\d.,]+) الأسبوع الماضي\.$/, function (m, a, b) { return 'Behind on ' + t(m).toLowerCase() + ': ' + a + ' sets this week, ' + b + ' last week.'; }]
  ]);

  /* ---------- v11.4 (batch 2) ---------- */
  GymI18n.add({
    'تعبّت الجلسة الخفيفة. احفظ كل جولة بعد ما تسويها': 'Light session filled in. Save each set after you do it',
    'مستوى قوتك مقابل وزنك': 'Your strength for your bodyweight',
    'سكوات': 'Squat', 'بنش بريس': 'Bench press', 'ديدليفت': 'Deadlift', 'ضغط أكتاف واقف': 'Overhead press',
    'بداية': 'Starting', 'مبتدئ': 'Beginner', 'متوسط': 'Intermediate', 'متقدم': 'Advanced', 'نخبة': 'Elite',
    'أدخل وزنك في البروفايل عشان نقارن قوتك بوزنك.': 'Enter your weight in Profile to compare your strength with it.',
    'سجّل سكوات أو بنش أو ديدليفت أو ضغط أكتاف بالبار، ويطلع مستواك هنا.': 'Log a barbell squat, bench, deadlift or overhead press and your level shows here.',
    'تقريبي: معايير منتشرة لقوة الرجال والنساء حسب وزن الجسم. العمر والخبرة يفرقون.': 'Approximate: common strength standards for men and women by bodyweight. Age and training years matter too.',
    'تقرير الشهر': 'Monthly report',
    'اختر الشهر': 'Choose the month',
    'ما فيه تمارين مسجلة في هالشهر للحين.': 'No workouts logged this month yet.',
    'جلسات': 'Sessions', 'جولات فعلية': 'Working sets', 'الحجم (طن)': 'Volume (t)', 'أرقام قياسية': 'Records',
    'نفس الشهر اللي قبله': 'Same as last month',
    'شارك كصورة': 'Share as image',
    'انحفظت صورة الجلسة': 'Session image saved',
    'تعذر تجهيز الصورة': "Couldn't make the image",
    'الجلسة غير موجودة': 'Session not found',
    'كسرت رقمك في': 'New record in'
  }, [
    [/^قوتك ثابتة من ([\d.,]+) جلسات\. هذا طبيعي، والحل غالبًا جلسة أخف: نزّل 10% وسوّ نفس العدات، والجلسة اللي بعدها ارجع لوزنك\.$/, function (n) { return 'Your strength has stalled for ' + n + ' sessions. That is normal, and a lighter session usually fixes it: drop 10%, do the same reps, then go back to your weight next time.'; }],
    [/^جلسة خفيفة: (.+)$/, function (a) { return 'Light session: ' + t(a); }],
    [/^1RM ([\d.,]+) كجم = ([\d.,]+)× وزنك(?: · باقي ([\d.,]+) كجم لـ(.+))?$/, function (rm, r, kg, lvl) { return '1RM ' + rm + ' kg = ' + r + '× your weight' + (kg ? ' · ' + kg + ' kg to ' + t(lvl) : ''); }],
    [/^([+−])([\d.,]+) عن الشهر اللي قبله$/, function (s, n) { return s + n + ' vs last month'; }],
    [/^أكثر عضلة اشتغلت عليها: (.+) \(([\d.,]+) جولة\)$/, function (m, n) { return 'Most trained: ' + t(m).toLowerCase() + ' (' + n + (n === '1' ? ' set)' : ' sets)'); }],
    [/^كارديو: ([\d.,]+) دقيقة$/, function (n) { return 'Cardio: ' + n + ' min'; }],
    [/^أيام التمرين: ([\d.,]+)$/, function (n) { return 'Training days: ' + n; }]
  ]);

  /* ---------- v11.5 (batch 3) ---------- */
  GymI18n.add({
    'استشفاء العضلات: وش جاهز اليوم': 'Muscle recovery: what is ready today',
    'من قدام': 'Front', 'من ورا': 'Back',
    'ما تمرنت عليها للحين': 'Not trained yet',
    'جاهزة': 'Ready',
    'تقدير من آخر جلسة لكل عضلة وكم جولة سويت: 1–4 جولات تحتاج يوم ونص، 5–9 يومين، و10 أو أكثر 3 أيام. النوم والأكل يفرقون.': 'Estimated from the last workout of each muscle and how many sets you did: 1–4 sets need a day and a half, 5–9 two days, 10 or more three days. Sleep and food matter too.',
    'عندي وقت:': 'Time I have:',
    'بدون حد': 'No limit',
    'ما فيه جولة أكررها': 'No set to repeat',
    '(اليمين)': '(right)',
    'يمين ويسار مختلفة؟': 'Different left and right?',
    'نفس العدات للجهتين': 'Same reps both sides',
    'عدات اليسار:': 'Left reps:',
    'عدات اليسار': 'Left reps',
    'عدات اليمين': 'Right reps',
    'عدات اليمين واليسار': 'Left and right reps',
    'عدات اليسار لازم رقم صحيح': 'Left reps must be a whole number',
    'أنقص عدات اليسار': 'Fewer left reps', 'زد عدات اليسار': 'More left reps',
    'صور التقدم': 'Progress photos',
    '+ أضف صورة': '+ Add photo',
    'خاصة: تنحفظ في جوالك بس، وما تدخل في النسخة الاحتياطية ولا تطلع لأي مكان. اضغط صورتين عشان تقارنهم.': 'Private: kept on your phone only, never in backups and never sent anywhere. Tap two photos to compare them.',
    'ما فيه صور للحين. صوّر نفسك كل أسبوعين بنفس المكان، وبتشوف الفرق اللي الميزان ما يبينه.': 'No photos yet. Take one every two weeks in the same spot, and you will see changes the scale does not show.',
    'صورة': 'Photo',
    'حذف': 'Delete',
    'حذف الصورة': 'Delete photo',
    'الصورة تنحذف من جوالك نهائيًا، وما ترجع.': 'The photo is deleted from your phone for good.',
    'حذف الصورة نهائيًا؟': 'Delete this photo for good?',
    'انحفظت الصورة في جوالك بس': 'Photo saved on your phone only',
    'انحذفت الصورة': 'Photo deleted',
    'اختر صورة ثانية عشان تقارنهم جنب بعض.': 'Pick a second photo to compare them side by side.',
    'اختر صورة (JPG أو PNG)': 'Choose a photo (JPG or PNG)',
    'الصورة كبيرة جدًا؛ الحد 30 ميجابايت': 'The photo is too large; the limit is 30 MB',
    'الملف مو صورة يقدر التطبيق يقراها': "The file isn't an image the app can read",
    'تعذر فتح تخزين الصور': "Couldn't open photo storage",
    'تعذر حفظ الصورة': "Couldn't save the photo",
    'التخزين غير متاح في هذا المتصفح': 'Storage is not available in this browser',
    '{0} يوم بين الصورتين. صوّر بنفس المكان والإضاءة عشان المقارنة تكون عادلة.': function (n) { return n + (n === '1' ? ' day' : ' days') + ' between the photos. Use the same spot and light so the comparison is fair.'; },
    'وصلت {0} صورة. احذف صور قديمة عشان تضيف جديدة': 'You have {0} photos. Delete old ones to add new photos'
  }, [
    [/^ترتاح كمان ([\d.,]+) ساعة تقريبًا$/, function (h) { return 'Needs about ' + h + (h === '1' ? ' more hour' : ' more hours'); }],
    [/^تقريبًا ([\d.,]+) دقيقة$/, function (m) { return 'About ' + m + ' min'; }],
    [/^الخطة تدخل في ([\d.,]+) دقيقة \(تقريبًا ([\d.,]+)\)\.$/, function (a, b) { return 'The plan fits in ' + a + ' min (about ' + b + ').'; }],
    [/^شلت (.+) عشان تخلص في ([\d.,]+) دقيقة تقريبًا\.$/, function (a, m) { return 'Removed ' + a.split('، ').map(t).join(', ') + ' so you finish in about ' + m + ' min.'; }],
    [/^(يسارك|يمينك) أضعف بـ ([\d]+)% في آخر 3 جلسات\. ابدأ باليسار، وخل اليمين يوقف على نفس عداته\.$|^(يمينك) أضعف بـ ([\d]+)% في آخر 3 جلسات\. ابدأ باليمين، وخل اليسار يوقف على نفس عداته\.$/, function (a, p, b, q) { return a ? 'Your left side is ' + p + '% weaker over the last 3 sessions. Start with the left and stop the right at the same reps.' : 'Your right side is ' + q + '% weaker over the last 3 sessions. Start with the right and stop the left at the same reps.'; }],
    [/^جاهز: (.+?)(?: · يرتاح: (.+))?$/, function (a, b) { return 'Ready: ' + a.split('، ').map(t).join(', ') + (b ? ' · Resting: ' + b.split('، ').map(t).join(', ') : ''); }],
    [/^يرتاح: (.+)$/, function (b) { return 'Resting: ' + b.split('، ').map(t).join(', '); }],
    [/^يمين ([\d]+) · يسار ([\d]+)$/, function (r, l) { return 'R ' + r + ' · L ' + l; }],
    [/^(.+) × ([\d]+)\/([\d]+)$/, function (w, r, l) { var x = t(w); return x == null ? null : x + ' × ' + r + '/' + l; }]
  ]);

  /* ---------- v11.6 (batch 4) ---------- */
  GymI18n.add({
    'طريقة الأداء': 'How to do it',
    'العضلات:': 'Muscles:',
    'أشهر الأغلاط:': 'Common mistakes:',
    'برنامج:': 'Program:',
    'بدون برنامج': 'No program',
    'الجاي': 'next',
    'هدف البرنامج': 'Program target',
    'سويت {0} من {1}': '{0} of {1} done',
    '{0} جولات × {1} عدات': '{0} sets × {1} reps',
    '{0} جولات × {1} ثانية': '{0} sets × {1} s',
    'جولة وحدة × {0} عدات': '1 set × {0} reps',
    'جولة وحدة × {0} ثانية': '1 set × {0} s',
    'ديدليفت بالبار': 'Barbell Deadlift',
    'دفع / سحب / أرجل (PPL)': 'Push / Pull / Legs (PPL)',
    'علوي / سفلي (Upper / Lower)': 'Upper / Lower',
    '5×5 للمبتدئين': '5×5 for beginners',
    'جسم كامل 3 أيام (Full Body)': 'Full Body, 3 days',
    'يوم أ (A)': 'Day A', 'يوم ب (B)': 'Day B', 'يوم ج (C)': 'Day C',
    'يوم {0}': 'Day {0}',
    'من {0} إلى {1} أيام بالأسبوع': '{0} to {1} days a week',
    '{0} أيام بالأسبوع': '{0} days a week',
    '{0} أيام بالأسبوع (أ، ب، أ… بالتناوب)': '{0} days a week (A, B, A… alternating)',
    '{0} أو {1} أيام بالأسبوع': '{0} or {1} days a week',
    '{0} أيام بالأسبوع وبينها يوم راحة': '{0} days a week with a rest day between',
    'لما تكمل أعلى العدات في كل الجولات، زد الوزن الجلسة الجاية. كرر الأيام الثلاثة مرة أو مرتين بالأسبوع.': 'When you hit the top of the rep range on every set, add weight next session. Run the three days once or twice a week.',
    'يومين علوي ويومين سفلي. التمارين المركبة أول وبأوزان ثقيلة، وزد الوزن لما توصل أعلى العدات.': 'Two upper and two lower days. Heavy compound lifts first; add weight when you reach the top of the rep range.',
    'لو كملت 5×5 كلها، زد 2.5 كجم الجلسة الجاية (الديدليفت 5 كجم). لو ما كملتها 3 مرات ورا بعض، نزّل 10% وابنِ من جديد.': 'If you complete all 5×5, add 2.5 kg next session (5 kg on the deadlift). If you miss it 3 times in a row, drop 10% and build back up.',
    'T1 (أول تمرين): 5×3 ثقيل، وآخر جولة أكثر عدات تقدر. T2: 3×10 متوسط. T3: 3×15 خفيف. لو فشلت في T1 انتقل لـ 6×2 بعدها 10×1.': 'T1 (first lift): heavy 5×3, last set as many reps as you can. T2: moderate 3×10. T3: light 3×15. If you fail T1, move to 6×2, then 10×1.',
    'كل يوم يشغّل الجسم كامل. زد الوزن لما توصل أعلى العدات في كل الجولات.': 'Every day trains the whole body. Add weight when you reach the top of the rep range on every set.',
    'وضع رمضان': 'Ramadan mode',
    'الاقتراح يثبّت الوزن بدل ما يزيده، تذكير بالماء بعد الفطور، والسعرات تنقسم على الفطور والسحور': 'Suggestions hold your weight instead of adding, a water reminder after iftar, and calories split between iftar and suhoor',
    'وقت الفطور تقريبًا': 'Iftar time (roughly)',
    'تذكير الماء يجيك بعده بربع ساعة': 'The water reminder comes 15 minutes after',
    'وضع رمضان: ثبّت نفس أرقام آخر مرة. الصيام يقلل طاقتك، والهدف تحافظ على قوتك لين يخلص الشهر.': 'Ramadan mode: repeat last time\'s numbers. Fasting lowers your energy, and the goal is to keep your strength until the month ends.',
    'وضع رمضان شغال: الاقتراح يثبّت الوزن، وتذكير الماء بعد الفطور': 'Ramadan mode on: suggestions hold your weight, and a water reminder after iftar',
    'وضع رمضان مطفي': 'Ramadan mode off',
    'اكتب وقت الفطور مثل 18:05': 'Enter the iftar time, like 18:05',
    'وقت الفطور': 'Iftar time',
    'رمضان: اشرب ماء بين الجولات، ولو كنت صايم خل الجلسة أقصر': 'Ramadan: drink water between sets, and keep the session shorter if you are fasting',
    'يوم البرنامج': 'Program day', 'البرنامج': 'Program'
  }, [
    [/^تذكير الماء الساعة ([\d:]+)$/, function (a) { return 'Water reminder at ' + a; }],
    [/^في رمضان: قسّم سعرات المحافظة \(([\d.,]+)\) على وجبتين: الفطور حوالي ([\d.,]+) سعرة، والسحور حوالي ([\d.,]+)\. خل البروتين في الوجبتين\.$/, function (a, b, c) { return 'In Ramadan: split your maintenance calories (' + a + ') over two meals: about ' + b + ' kcal at iftar and ' + c + ' at suhoor. Keep protein in both.'; }],
    [/^(.+?) ((?:\d+ جولات|جولة وحدة) × [\d-]+ (?:عدات|ثانية))$/, function (n, x) { return t(n) + ' ' + t(x); }]
  ]);

  /* ---------- v11.7 (stage 1) ---------- */
  GymI18n.add({
    'اليوم': 'Today', 'أمس': 'Yesterday',
    '({0} ما له قرص)': '({0} with no plate)', '{0} ({1} ما له قرص)': '{0} ({1} with no plate)',
    'حجم الخط': 'Text size', 'يكبّر كل النصوص والأرقام': 'Makes all text and numbers bigger',
    'عادي': 'Normal', 'كبير': 'Large', 'أكبر': 'Larger',
    'رجع الخط لحجمه العادي': 'Text back to normal size', 'كبّرت الخط': 'Text is larger', 'كبّرت الخط أكثر': 'Text is even larger',
    'العضلة': 'Muscle', 'وحدة التمرين': 'Exercise unit'
  });

})();
