/*
 * Gym Tracker — شرح مكتوب لكل تمرين (v11.6، D2).
 * لكل تمرين: العضلات، ثلاث خطوات، وأشهر غلطتين. بالعربي والإنجليزي، وكله نص عشان التطبيق يبقى خفيف ويشتغل بدون نت.
 * الترتيب: [العضلات عربي، العضلات إنجليزي، [خطوات عربي×3]، [خطوات إنجليزي×3]، [أغلاط عربي×2]، [أغلاط إنجليزي×2]]
 */
(function () {
  'use strict';
  var G = {
    ex_1: ['صدر، كتف أمامي، ترايسبس', 'Chest, front delts, triceps',
      ['استلق وعيونك تحت البار، ورجولك ثابتة على الأرض، ولوحي كتفك مضمومين.', 'نزّل البار لأسفل الصدر وكوعك بزاوية 45 درجة تقريبًا عن جسمك.', 'ادفع لفوق لين تمد ذراعك، والبار يمشي بخط مستقيم فوق الكتف.'],
      ['Lie with your eyes under the bar, feet planted, shoulder blades pulled together.', 'Lower the bar to your lower chest with elbows about 45° from your body.', 'Press up until your arms are straight, the bar ending over your shoulders.'],
      ['ترفع المقعدة عن البنش وقت الدفع.', 'تخبط البار في صدرك وتعتمد على الارتداد.'],
      ['Lifting your hips off the bench as you press.', 'Bouncing the bar off your chest.']],
    ex_2: ['أعلى الصدر، كتف أمامي، ترايسبس', 'Upper chest, front delts, triceps',
      ['اضبط البنش على ميلان 30 درجة تقريبًا، والقدمين ثابتة.', 'نزّل البار لأعلى الصدر تحت الترقوة بشوي.', 'ادفع لفوق وللخلف شوي لين يصير البار فوق كتفك.'],
      ['Set the bench to about 30°, feet planted.', 'Lower the bar to your upper chest, just under the collarbone.', 'Press up and slightly back until the bar is over your shoulders.'],
      ['ميلان عالي جدًا فيصير التمرين أكتاف.', 'تفرد الكوعين على الجنب 90 درجة.'],
      ['Setting the incline so steep it becomes a shoulder press.', 'Flaring the elbows straight out to the sides.']],
    ex_3: ['صدر، كتف أمامي، ترايسبس', 'Chest, front delts, triceps',
      ['اجلس والدمبلات على فخذك، واستلق وارفعهم فوق صدرك.', 'نزّلهم على جنب الصدر لين تحس بتمدد خفيف.', 'ادفعهم لفوق وقرّبهم من بعض بدون ما يتصادمون.'],
      ['Sit with the dumbbells on your thighs, lie back and bring them over your chest.', 'Lower them beside your chest until you feel a light stretch.', 'Press up and bring them together without clanking.'],
      ['تنزل أعمق من اللي يتحمله كتفك.', 'كل يد تمشي بسرعة مختلفة.'],
      ['Going deeper than your shoulders can handle.', 'Letting one hand move faster than the other.']],
    ex_4: ['أعلى الصدر، كتف أمامي', 'Upper chest, front delts',
      ['البنش على 30 درجة، والدمبلات فوق أعلى الصدر.', 'نزّلهم ببطء على جنب أعلى الصدر، والكوعين تحت الدمبل.', 'ادفع لفوق لين تمد ذراعك وتعصر الصدر فوق.'],
      ['Bench at about 30°, dumbbells over your upper chest.', 'Lower them slowly beside your upper chest, elbows under the weights.', 'Press up until your arms are straight and squeeze at the top.'],
      ['ميلان عالي يحوّل الشغل للأكتاف.', 'ظهرك يتقوس بقوة عن البنش.'],
      ['An incline so high the shoulders take over.', 'Arching hard off the bench.']],
    ex_5: ['أسفل الصدر، ترايسبس', 'Lower chest, triceps',
      ['ثبّت رجولك في البنش المنحدر واستلق براحة.', 'نزّل الدمبلات لأسفل الصدر.', 'ادفع لفوق وتحكّم بالنزول.'],
      ['Hook your feet on the decline bench and lie back carefully.', 'Lower the dumbbells to your lower chest.', 'Press up and control the way down.'],
      ['تقوم من البنش بسرعة والدمبلات في يدك.', 'تنزل بسرعة بدون تحكم.'],
      ['Sitting up quickly with the dumbbells still in your hands.', 'Dropping the weights without control.']],
    ex_6: ['صدر', 'Chest',
      ['استلق والدمبلات فوق صدرك، وكوعك مثني شوي وثابت.', 'افتح يدينك على الجنب بقوس واسع لين تحس بتمدد.', 'رجّعهم بنفس القوس كأنك تحضن شجرة.'],
      ['Lie back with the dumbbells over your chest, elbows slightly bent and fixed.', 'Open your arms out in a wide arc until you feel a stretch.', 'Bring them back along the same arc, like hugging a tree.'],
      ['تثني الكوع وتحوّلها ضغط.', 'وزن ثقيل يجبرك تنزل أعمق من اللازم.'],
      ['Bending the elbows until it turns into a press.', 'Going so heavy you drop too deep.']],
    ex_7: ['صدر، ترايسبس', 'Chest, triceps',
      ['اضبط المقعد لين تكون المقابض على مستوى وسط الصدر.', 'ادفع لقدام لين تمد ذراعك بدون ما تقفل الكوع.', 'رجّع ببطء لين تحس بتمدد خفيف في الصدر.'],
      ['Set the seat so the handles line up with mid-chest.', 'Press forward until your arms are straight without locking hard.', 'Return slowly until you feel a light chest stretch.'],
      ['المقعد منخفض أو مرتفع زيادة.', 'تبعد ظهرك عن المسند وقت الدفع.'],
      ['Seat set too low or too high.', 'Pulling your back off the pad as you press.']],
    ex_8: ['أعلى الصدر، كتف أمامي', 'Upper chest, front delts',
      ['اضبط المقعد لين تكون المقابض عند أعلى الصدر.', 'ادفع لفوق ولقدام بحركة ثابتة.', 'رجّع بتحكم بدون ما يلمس الوزن الكومة.'],
      ['Set the seat so the handles sit at your upper chest.', 'Press up and forward smoothly.', 'Come back under control without resting the stack.'],
      ['ترفع كتفك لأذنك.', 'تستعجل في النزول.'],
      ['Shrugging your shoulders toward your ears.', 'Rushing the way back.']],
    ex_9: ['صدر', 'Chest',
      ['اضبط المقعد لين تكون المقابض على مستوى الكتف.', 'قرّب المقابض لقدام وأنت تعصر الصدر.', 'رجّع ببطء لين تحس بتمدد، وكوعك مثني شوي.'],
      ['Set the seat so the handles are level with your shoulders.', 'Bring the handles together while squeezing your chest.', 'Return slowly to a stretch, elbows slightly bent.'],
      ['ترجع لورا أبعد من اللي يتحمله الكتف.', 'تدفع بيدك بدل ما تحرك من الصدر.'],
      ['Letting the arms travel further back than your shoulders like.', 'Pushing with your hands instead of moving from the chest.']],
    ex_10: ['صدر', 'Chest',
      ['قف بين الكيبلين وخطوة لقدام، وجسمك مايل شوي.', 'اسحب المقابض لتحت وقدام لين يتقابلون قدام صدرك.', 'رجّع ببطء لين تحس بتمدد، والكوع مثني شوي وثابت.'],
      ['Stand between the cables, one step forward, leaning slightly.', 'Pull the handles down and forward until they meet in front of your chest.', 'Return slowly to a stretch, elbows slightly bent and fixed.'],
      ['تستخدم وزن جسمك وتتمرجح.', 'تثني الكوع وتحولها ضغط.'],
      ['Swinging your body weight into it.', 'Bending the elbows until it becomes a press.']],
    ex_11: ['أكتاف، ترايسبس، ثبات الجذع', 'Shoulders, triceps, core',
      ['قف والبار على أعلى صدرك، والقبضة أعرض من الكتف بشوي.', 'شد بطنك ومقعدتك، وادفع البار لفوق ورأسك يرجع لورا شوي.', 'لما يعدي البار رأسك دخّل رأسك تحته، وانزل بتحكم.'],
      ['Stand with the bar on your upper chest, grip just wider than your shoulders.', 'Brace your abs and glutes and press up, moving your head back slightly.', 'Once the bar passes your head, bring your head through and lower under control.'],
      ['تقوّس أسفل ظهرك عشان ترفع.', 'تدفع البار لقدام بدل فوق.'],
      ['Arching your lower back to get the weight up.', 'Pushing the bar forward instead of straight up.']],
    ex_12: ['أكتاف، ترايسبس', 'Shoulders, triceps',
      ['اجلس والظهر على المسند، والدمبلات على مستوى الأذن.', 'ادفعهم لفوق لين يقربون من بعض.', 'نزّلهم ببطء لمستوى الأذن.'],
      ['Sit with your back on the pad and the dumbbells at ear level.', 'Press them up until they nearly meet.', 'Lower slowly back to ear level.'],
      ['تبعد ظهرك عن المسند وتتقوس.', 'تنزل جزء بسيط بس من الحركة.'],
      ['Arching away from the backrest.', 'Doing only a small part of the movement.']],
    ex_13: ['أكتاف (أمامي وجانبي)', 'Shoulders (front and side)',
      ['ابدأ والدمبلات قدام وجهك وكفك لجهتك.', 'وأنت تدفع لفوق لف كفك لقدام.', 'نزّل وأنت تعكس اللفة لين ترجع كفك لجهتك.'],
      ['Start with the dumbbells in front of your face, palms facing you.', 'Rotate your palms forward as you press up.', 'Reverse the rotation on the way down.'],
      ['تستعجل فتضيع اللفة.', 'وزن ثقيل يخليك تتقوس.'],
      ['Rushing so the rotation gets lost.', 'Going so heavy you arch your back.']],
    ex_14: ['أكتاف، ترايسبس', 'Shoulders, triceps',
      ['اضبط المقعد لين تكون المقابض عند مستوى الكتف.', 'ادفع لفوق بدون ما تقفل الكوع بقوة.', 'نزّل بتحكم لمستوى الكتف.'],
      ['Set the seat so the handles start at shoulder height.', 'Press up without slamming the elbows straight.', 'Lower under control to shoulder height.'],
      ['المقعد منخفض فتبدأ من تحت الكتف بكثير.', 'تتمرجح بالجذع.'],
      ['Seat so low you start far below the shoulders.', 'Rocking your torso.']],
    ex_15: ['كتف جانبي', 'Side delts',
      ['قف والدمبلات على جنبك، والكوع مثني شوي.', 'ارفعهم على الجنب لين مستوى الكتف، والخنصر أعلى شوي من الإبهام.', 'نزّل ببطء بدون ما ترتاح تحت.'],
      ['Stand with the dumbbells at your sides, elbows slightly bent.', 'Raise them out to shoulder height, leading with the elbows.', 'Lower slowly without resting at the bottom.'],
      ['تتمرجح بجسمك عشان ترفع الوزن.', 'ترفع كتفك لأذنك فتشتغل الترابيس بدال الكتف.'],
      ['Swinging your body to lift the weight.', 'Shrugging so the traps do the work.']],
    ex_16: ['كتف جانبي', 'Side delts',
      ['قف جنب الكيبل وامسك المقبض باليد البعيدة.', 'ارفع ذراعك على الجنب لين مستوى الكتف.', 'نزّل ببطء، والكيبل يخلي الشد ثابت طول الحركة.'],
      ['Stand side-on to the cable and hold the handle with your far hand.', 'Raise your arm out to shoulder height.', 'Lower slowly; the cable keeps tension the whole way.'],
      ['تميل بجسمك بعيد عشان تساعد نفسك.', 'ترفع فوق مستوى الكتف بكثير.'],
      ['Leaning away to help yourself.', 'Lifting well above shoulder height.']],
    ex_17: ['كتف جانبي', 'Side delts',
      ['اضبط المقعد لين يكون مفصل الجهاز على مستوى كتفك.', 'ارفع ذراعك على الجنب بالكوع، مو باليد.', 'نزّل ببطء بدون ما يلمس الوزن.'],
      ['Set the seat so the machine pivot lines up with your shoulder.', 'Raise your arms out, pushing with the elbows, not the hands.', 'Lower slowly without letting the stack touch.'],
      ['ترفع كتفك لأذنك.', 'تستعجل وتخبط الوزن تحت.'],
      ['Shrugging up to your ears.', 'Rushing and dropping the stack.']],
    ex_18: ['كتف أمامي', 'Front delts',
      ['قف والدمبلات قدام فخذك.', 'ارفعهم لقدام لين مستوى الكتف، والكوع مثني شوي.', 'نزّل ببطء.'],
      ['Stand with the dumbbells in front of your thighs.', 'Raise them forward to shoulder height, elbows slightly bent.', 'Lower slowly.'],
      ['تتمرجح لورا بظهرك.', 'ترفع أعلى من الكتف بكثير.'],
      ['Leaning back with your lower back.', 'Lifting far above shoulder height.']],
    ex_19: ['صدر سفلي، ترايسبس، كتف أمامي', 'Lower chest, triceps, front delts',
      ['امسك المقابض وارفع نفسك لين تمد ذراعك.', 'انزل لين يكون كوعك بزاوية 90 درجة تقريبًا، وجسمك مايل لقدام شوي.', 'ادفع لفوق لين تمد ذراعك.'],
      ['Grip the bars and lift yourself until your arms are straight.', 'Lower until your elbows are about 90°, leaning slightly forward.', 'Push back up to straight arms.'],
      ['تنزل أعمق من اللي يتحمله كتفك.', 'كتفك يرتفع لأذنك تحت.'],
      ['Dropping deeper than your shoulders can handle.', 'Letting the shoulders shrug up at the bottom.']],
    ex_20: ['ترايسبس', 'Triceps',
      ['قف قدام الكيبل والكوعين لاصقة بجنبك.', 'ادفع البار لتحت لين تمد ذراعك كامل.', 'رجّع ببطء لين مستوى الصدر، والكوع ما يتحرك.'],
      ['Stand facing the cable with elbows pinned to your sides.', 'Push the bar down until your arms are fully straight.', 'Return slowly to chest level without moving the elbows.'],
      ['كوعك يتحرك لقدام وورا.', 'تميل بجسمك فوق البار وتدفع بوزنك.'],
      ['Letting the elbows drift forward and back.', 'Leaning over the bar and pushing with your body weight.']],
    ex_21: ['ترايسبس', 'Triceps',
      ['امسك الحبل والكوعين لاصقة بجنبك.', 'ادفع لتحت وافتح الحبل على الجنب آخر الحركة.', 'رجّع ببطء لين مستوى الصدر.'],
      ['Hold the rope with elbows pinned to your sides.', 'Push down and spread the rope apart at the bottom.', 'Return slowly to chest level.'],
      ['تحرك الكتف مع الحركة.', 'وزن ثقيل يخليك ما تفتح الحبل.'],
      ['Moving the shoulders with the rope.', 'Going so heavy you can’t spread the rope.']],
    ex_22: ['ترايسبس (الرأس الطويل)', 'Triceps (long head)',
      ['امسك دمبل بيدينك فوق رأسك.', 'نزّله ورا رأسك والكوعين لفوق وقريبة من بعض.', 'مد ذراعك لفوق لين تستقيم.'],
      ['Hold one dumbbell with both hands overhead.', 'Lower it behind your head, elbows pointing up and close together.', 'Extend your arms back up to straight.'],
      ['الكوعين يتفتحون على الجنب.', 'تقوس ظهرك وأنت تمد.'],
      ['Letting the elbows flare out.', 'Arching your back as you extend.']],
    ex_23: ['ترايسبس', 'Triceps',
      ['مِل لقدام وظهرك مستقيم، والعضد لاصق بجنبك.', 'مد ذراعك لورا لين تستقيم.', 'رجّع ببطء بدون ما يتحرك العضد.'],
      ['Hinge forward with a flat back, upper arm tight to your side.', 'Extend your arm back until it is straight.', 'Return slowly without moving the upper arm.'],
      ['تتمرجح بالوزن.', 'العضد ينزل وانت ترجع.'],
      ['Swinging the weight.', 'Letting the upper arm drop as you return.']],
    ex_24: ['ظهر عريض (لاتس)، بايسبس', 'Lats, biceps',
      ['اجلس وثبّت فخذك تحت المسند، وامسك البار أعرض من الكتف.', 'اسحب البار لأعلى صدرك وأنت تنزل كتفك وتقرب الكوع لجنبك.', 'رجّع ببطء لين تمد ذراعك فوق.'],
      ['Sit with thighs under the pad and grip the bar wider than your shoulders.', 'Pull the bar to your upper chest, driving your elbows down to your sides.', 'Return slowly until your arms are straight overhead.'],
      ['تميل لورا بقوة وتسحب بوزن جسمك.', 'تسحب البار ورا رقبتك.'],
      ['Leaning way back and pulling with your body weight.', 'Pulling the bar behind your neck.']],
    ex_25: ['ظهر عريض، وسط الظهر، بايسبس', 'Lats, mid back, biceps',
      ['امسك المقبض الضيق واجلس ثابت.', 'اسحب لأعلى صدرك والكوعين قريبة من جسمك.', 'رجّع ببطء لين تحس بتمدد في الظهر.'],
      ['Take the close grip handle and sit tall.', 'Pull to your upper chest with elbows close to your body.', 'Return slowly to a stretch in your back.'],
      ['تسحب بيدك بدل ظهرك.', 'تقوس رقبتك لقدام.'],
      ['Pulling with your arms instead of your back.', 'Craning your neck forward.']],
    ex_26: ['وسط الظهر، ظهر عريض، بايسبس', 'Mid back, lats, biceps',
      ['اجلس والرجول على المسند وركبتك مثنية شوي، وظهرك مستقيم.', 'اسحب المقبض لبطنك وضم لوحي كتفك.', 'رجّع ببطء لين تمد ذراعك بدون ما تنحني بظهرك.'],
      ['Sit with feet on the platform, knees slightly bent, back straight.', 'Pull the handle to your belly and squeeze your shoulder blades together.', 'Return slowly to straight arms without rounding your back.'],
      ['تتمرجح لقدام وورا بالجذع.', 'تدوّر ظهرك وأنت ترجع.'],
      ['Rocking your torso back and forth.', 'Rounding your back on the way forward.']],
    ex_27: ['ظهر عريض، وسط الظهر، بايسبس', 'Lats, mid back, biceps',
      ['حط ركبة ويد على البنش، وظهرك مستقيم.', 'اسحب الدمبل لجنب وسطك والكوع قريب من جسمك.', 'نزّل ببطء لين تمد ذراعك.'],
      ['Put one knee and hand on the bench, back flat.', 'Row the dumbbell to your hip with your elbow close to your body.', 'Lower slowly to a straight arm.'],
      ['تلف جسمك عشان ترفع الوزن.', 'تسحب للصدر بدل الورك.'],
      ['Twisting your torso to lift the weight.', 'Pulling to your chest instead of your hip.']],
    ex_28: ['وسط الظهر، ظهر عريض، أسفل الظهر', 'Mid back, lats, lower back',
      ['امسك البار ومِل لقدام لين جسمك قريب من 45 درجة، والظهر مستقيم.', 'اسحب البار لأسفل صدرك أو بطنك.', 'نزّل بتحكم بدون ما يتغير ميلان جسمك.'],
      ['Hold the bar and hinge to about 45°, back flat.', 'Row the bar to your lower chest or belly.', 'Lower under control without changing your torso angle.'],
      ['تدوّر أسفل ظهرك.', 'تقوم بجسمك مع كل عدة.'],
      ['Rounding your lower back.', 'Standing up a little more with every rep.']],
    ex_29: ['وسط الظهر، ظهر عريض', 'Mid back, lats',
      ['اوقف على الجهاز وصدرك على المسند إذا فيه.', 'اسحب المقابض لصدرك وضم لوحي كتفك.', 'نزّل ببطء لين تمد ذراعك.'],
      ['Set up on the machine, chest on the pad if it has one.', 'Pull the handles to your chest and squeeze your shoulder blades.', 'Lower slowly to straight arms.'],
      ['تتمرجح بجسمك.', 'تدوّر ظهرك تحت.'],
      ['Jerking with your body.', 'Rounding your back at the bottom.']],
    ex_30: ['وسط الظهر، ظهر عريض', 'Mid back, lats',
      ['اضبط المقعد وصدرك على المسند.', 'اسحب المقابض لتحت ولورا والكوعين لجنبك.', 'رجّع ببطء لين تحس بتمدد.'],
      ['Set the seat with your chest against the pad.', 'Pull the handles down and back, elbows to your sides.', 'Return slowly to a stretch.'],
      ['تبعد صدرك عن المسند.', 'تسحب بيدك بس.'],
      ['Pulling your chest off the pad.', 'Pulling only with your arms.']],
    ex_31: ['ظهر عريض، بايسبس، ساعد', 'Lats, biceps, forearms',
      ['تعلّق في البار والقبضة أعرض من الكتف شوي (أو ضيقة وكفك لجهتك للبايسبس).', 'اسحب نفسك لين يعدي ذقنك البار، وصدرك يقرب من البار.', 'انزل ببطء لين تمد ذراعك.'],
      ['Hang from the bar, grip a little wider than your shoulders (or close, palms facing you, for chin-ups).', 'Pull until your chin clears the bar, chest toward it.', 'Lower slowly to straight arms.'],
      ['تتمرجح برجولك (كيبنق) بدون ما تقصد.', 'تنزل نص المسافة بس.'],
      ['Swinging your legs without meaning to.', 'Only coming halfway down.']],
    ex_32: ['ظهر عريض، بايسبس', 'Lats, biceps',
      ['اختار وزن المساعدة؛ كل ما زاد صار أسهل.', 'اركع على المسند وامسك المقابض، واسحب لين ذقنك فوق المقبض.', 'انزل ببطء. التقدم هنا = تنقص المساعدة.'],
      ['Pick the assist weight; more assist makes it easier.', 'Kneel on the pad, grip the handles and pull until your chin is above them.', 'Lower slowly. Progress here means less assist.'],
      ['مساعدة كثيرة لدرجة إن الحركة صارت ما تتعب.', 'تنزل بسرعة ويرتدك المسند.'],
      ['So much assist the set stops being work.', 'Dropping fast and letting the pad bounce you.']],
    ex_33: ['ظهر عريض، صدر', 'Lats, chest',
      ['استلق على البنش وامسك دمبل بيدينك فوق صدرك.', 'نزّله ورا رأسك بقوس، والكوع مثني شوي.', 'رجّعه فوق صدرك بنفس القوس.'],
      ['Lie on the bench holding one dumbbell over your chest with both hands.', 'Lower it back behind your head in an arc, elbows slightly bent.', 'Bring it back over your chest along the same arc.'],
      ['تنزل أبعد من اللي يتحمله كتفك.', 'تثني الكوع وتحولها ترايسبس.'],
      ['Going further back than your shoulders like.', 'Bending the elbows until it becomes a triceps move.']],
    ex_34: ['كتف خلفي، وسط الظهر', 'Rear delts, upper back',
      ['اجلس وصدرك على المسند، والمقابض على مستوى الكتف.', 'افتح ذراعك لورا على الجنب.', 'رجّع ببطء بدون ما يلمس الوزن.'],
      ['Sit with your chest on the pad and the handles at shoulder height.', 'Open your arms back and out to the sides.', 'Return slowly without the stack touching.'],
      ['تضم لوحي الكتف بقوة فيشتغل الظهر بدل الكتف الخلفي.', 'تتمرجح بالوزن.'],
      ['Pinching the shoulder blades so hard the back takes over.', 'Swinging the weight.']],
    ex_35: ['كتف خلفي', 'Rear delts',
      ['مِل لقدام وظهرك مستقيم، والدمبلات تحت صدرك.', 'افتحهم على الجنب لين مستوى الكتف، والكوع مثني شوي.', 'نزّل ببطء.'],
      ['Hinge forward with a flat back, dumbbells under your chest.', 'Raise them out to the sides to shoulder height, elbows slightly bent.', 'Lower slowly.'],
      ['تقوم بجسمك مع كل عدة.', 'وزن ثقيل يحوّلها سحب ظهر.'],
      ['Standing up with every rep.', 'Going so heavy it turns into a row.']],
    ex_36: ['كتف خلفي، وسط الظهر', 'Rear delts, upper back',
      ['اضبط الكيبل على مستوى الوجه وامسك الحبل.', 'اسحب الحبل لوجهك وافتحه على الجنب، والكوع فوق.', 'رجّع ببطء.'],
      ['Set the cable at face height and hold the rope.', 'Pull the rope to your face and split it apart, elbows high.', 'Return slowly.'],
      ['الكوع ينزل فتصير سحب عادي.', 'تميل لورا بجسمك.'],
      ['Dropping the elbows so it becomes a plain row.', 'Leaning back with your body.']],
    ex_37: ['ترابيس', 'Traps',
      ['قف والدمبلات على جنبك.', 'ارفع كتفك لفوق لأذنك وثبّت ثانية.', 'نزّل ببطء.'],
      ['Stand with the dumbbells at your sides.', 'Lift your shoulders straight up toward your ears and hold a second.', 'Lower slowly.'],
      ['تدوّر كتفك.', 'تثني ذراعك وتسحب.'],
      ['Rolling your shoulders.', 'Bending your arms to pull.']],
    ex_38: ['بايسبس', 'Biceps',
      ['قف والبار في يدك، والكوعين لجنبك.', 'ارفع البار لصدرك بدون ما يتحرك الكوع.', 'نزّل ببطء لين تمد ذراعك.'],
      ['Stand holding the bar, elbows at your sides.', 'Curl the bar to your chest without moving the elbows.', 'Lower slowly to straight arms.'],
      ['تتمرجح بظهرك.', 'تنزل نص الطريق بس.'],
      ['Swinging with your lower back.', 'Only lowering halfway.']],
    ex_39: ['بايسبس', 'Biceps',
      ['قف والدمبلات على جنبك وكفك لقدام.', 'ارفعهم لكتفك والكوع ثابت.', 'نزّل ببطء.'],
      ['Stand with the dumbbells at your sides, palms forward.', 'Curl them to your shoulders, elbows still.', 'Lower slowly.'],
      ['الكوع يطلع لقدام.', 'تتمرجح بجسمك.'],
      ['Letting the elbows drift forward.', 'Swinging your body.']],
    ex_40: ['بايسبس، عضلة الساعد (براكياليس)', 'Biceps, brachialis, forearms',
      ['امسك الدمبلات وكفك لجهة جسمك مثل المطرقة.', 'ارفعهم لكتفك بنفس القبضة.', 'نزّل ببطء.'],
      ['Hold the dumbbells with palms facing your body, like a hammer.', 'Curl them to your shoulders keeping that grip.', 'Lower slowly.'],
      ['تلف كفك وتحولها مرجحة عادية.', 'تتمرجح.'],
      ['Rotating the palms into a normal curl.', 'Swinging.']],
    ex_41: ['بايسبس (الرأس الطويل)', 'Biceps (long head)',
      ['استلق على بنش مائل وذراعك متدلية تحت.', 'ارفع الدمبلات بدون ما يتقدم الكوع.', 'نزّل ببطء لين تمد كامل.'],
      ['Lie back on an incline bench with arms hanging straight down.', 'Curl the dumbbells without moving the elbows forward.', 'Lower slowly all the way.'],
      ['ترفع الكتف عن البنش.', 'وزن ثقيل يقصّر الحركة.'],
      ['Lifting your shoulders off the bench.', 'Going so heavy the range gets shorter.']],
    ex_42: ['بايسبس', 'Biceps',
      ['قف قدام الكيبل والمقبض تحت.', 'ارفع لصدرك والكوعين ثابتة.', 'نزّل ببطء، والكيبل يخلي الشد ثابت.'],
      ['Stand facing the low cable.', 'Curl to your chest with elbows fixed.', 'Lower slowly; the cable keeps tension the whole time.'],
      ['تميل لورا.', 'الكوع يتحرك.'],
      ['Leaning back.', 'Letting the elbows move.']],
    ex_43: ['بايسبس', 'Biceps',
      ['اجلس وحط ظهر عضدك على داخل فخذك.', 'ارفع الدمبل لكتفك ببطء.', 'نزّل لين تمد ذراعك.'],
      ['Sit and rest the back of your upper arm against your inner thigh.', 'Curl the dumbbell slowly toward your shoulder.', 'Lower until your arm is straight.'],
      ['ترفع العضد عن الفخذ.', 'تستعجل.'],
      ['Lifting the arm off your thigh.', 'Rushing the reps.']],
    ex_44: ['فخذ أمامي، مقعدة، فخذ خلفي، أسفل الظهر', 'Quads, glutes, hamstrings, lower back',
      ['البار على أعلى ظهرك، والرجول بعرض الكتف وأصابعك لبرا شوي.', 'خذ نفس وشد بطنك، وانزل كأنك تقعد على كرسي لين يصير فخذك موازي للأرض أو أعمق.', 'ادفع الأرض بكامل رجلك وقوم، والركبة تمشي بنفس اتجاه أصابعك.'],
      ['Bar on your upper back, feet shoulder-width, toes slightly out.', 'Breathe in, brace, and sit down until your thighs are at least parallel.', 'Drive through your whole foot to stand, knees tracking over your toes.'],
      ['الركبة تدخل لجوا وأنت طالع.', 'كعبك يرتفع عن الأرض.'],
      ['Knees caving in on the way up.', 'Heels lifting off the floor.']],
    ex_45: ['فخذ أمامي، مقعدة', 'Quads, glutes',
      ['البار على أعلى ظهرك، ورجولك قدام البار شوي.', 'انزل لين فخذك موازي للأرض.', 'ادفع وقوم بدون ما تقفل الركبة بقوة.'],
      ['Bar on your upper back, feet slightly in front of the bar.', 'Lower until your thighs are parallel to the floor.', 'Drive up without snapping your knees locked.'],
      ['رجولك تحت البار مباشرة فتضغط على الركبة.', 'تنزل شوي بس.'],
      ['Feet directly under the bar, loading the knees.', 'Going only a little way down.']],
    ex_46: ['فخذ أمامي، مقعدة', 'Quads, glutes',
      ['ظهرك على المسند والكتف تحت الوسائد، ورجولك بعرض الكتف.', 'انزل ببطء لين ركبتك 90 درجة أو أعمق.', 'ادفع بكامل رجلك وقوم.'],
      ['Back on the pad, shoulders under the cushions, feet shoulder-width.', 'Lower slowly until your knees are at 90° or deeper.', 'Push through your whole foot to stand.'],
      ['ترفع كعبك.', 'تقفل الركبة بقوة فوق.'],
      ['Lifting your heels.', 'Slamming the knees locked at the top.']],
    ex_47: ['فخذ أمامي، مقعدة، فخذ خلفي', 'Quads, glutes, hamstrings',
      ['اجلس وظهرك كامل على المسند، ورجولك بعرض الكتف على المنصة.', 'نزّل المنصة لين ركبتك 90 درجة تقريبًا.', 'ادفع بدون ما تقفل الركبة.'],
      ['Sit with your whole back on the pad, feet shoulder-width on the platform.', 'Lower the platform until your knees are about 90°.', 'Press without locking your knees.'],
      ['أسفل ظهرك يرتفع عن المسند تحت.', 'تقفل الركبة فوق.'],
      ['Your lower back lifting off the pad at the bottom.', 'Locking your knees at the top.']],
    ex_48: ['فخذ أمامي، مقعدة', 'Quads, glutes',
      ['امسك الدمبل قدام صدرك عمودي.', 'انزل بين رجولك وصدرك مرفوع.', 'قوم وادفع الأرض بكامل رجلك.'],
      ['Hold the dumbbell upright against your chest.', 'Squat down between your legs, chest up.', 'Stand up driving through your whole foot.'],
      ['تميل لقدام وتدوّر ظهرك.', 'الركبة تدخل لجوا.'],
      ['Leaning forward and rounding your back.', 'Knees caving in.']],
    ex_49: ['فخذ أمامي', 'Quads',
      ['اضبط المسند فوق الكاحل، وركبتك على محور الجهاز.', 'مد رجلك لين تستقيم وثبّت ثانية.', 'نزّل ببطء.'],
      ['Set the pad just above your ankles with knees lined up with the pivot.', 'Straighten your legs and hold a second.', 'Lower slowly.'],
      ['ترفس الوزن بسرعة.', 'ترفع المقعدة عن المقعد.'],
      ['Kicking the weight up fast.', 'Lifting your hips off the seat.']],
    ex_50: ['فخذ خلفي', 'Hamstrings',
      ['اجلس واضبط المسند فوق الكعب، والفخذ مثبت.', 'اثني رجلك لتحت قد ما تقدر.', 'رجّع ببطء.'],
      ['Sit with the pad above your heels and thighs locked in.', 'Bend your knees as far as you can.', 'Return slowly.'],
      ['ترجع بسرعة وتخلي الوزن يسحبك.', 'ترفع المقعدة.'],
      ['Letting the weight snap back.', 'Lifting your hips.']],
    ex_51: ['فخذ خلفي', 'Hamstrings',
      ['انبطح والمسند فوق الكعب، والركبة على طرف البنش.', 'اثني رجلك لمقعدتك.', 'نزّل ببطء.'],
      ['Lie face down with the pad above your heels, knees at the bench edge.', 'Curl your heels toward your glutes.', 'Lower slowly.'],
      ['ترفع الورك عن البنش.', 'تنزل بسرعة.'],
      ['Lifting your hips off the bench.', 'Dropping the weight quickly.']],
    ex_52: ['فخذ خلفي، مقعدة، أسفل الظهر', 'Hamstrings, glutes, lower back',
      ['قف والبار قدام فخذك، والركبة مثنية شوي.', 'ادفع الورك لورا والبار ينزل لاصق برجلك، والظهر مستقيم، لين تحس بشد خلف الفخذ.', 'ارجع واقف وأنت تدفع الورك لقدام.'],
      ['Stand with the bar at your thighs, knees slightly bent.', 'Push your hips back, sliding the bar down your legs with a flat back, until your hamstrings stretch.', 'Stand back up by driving your hips forward.'],
      ['تدوّر ظهرك.', 'تثني الركبة وتحولها سكوات.'],
      ['Rounding your back.', 'Bending the knees until it becomes a squat.']],
    ex_53: ['فخذ خلفي، مقعدة', 'Hamstrings, glutes',
      ['امسك الدمبلات قدام فخذك والركبة مثنية شوي.', 'ادفع الورك لورا والدمبلات تنزل قريبة من رجلك، والظهر مستقيم.', 'ارجع واقف بدفع الورك.'],
      ['Hold the dumbbells in front of your thighs, knees slightly bent.', 'Push your hips back, dumbbells close to your legs, back flat.', 'Stand up by driving your hips forward.'],
      ['الدمبلات تبعد عن رجلك.', 'تدوّر ظهرك.'],
      ['Letting the dumbbells drift away from your legs.', 'Rounding your back.']],
    ex_54: ['فخذ أمامي، مقعدة', 'Quads, glutes',
      ['قف والدمبلات على جنبك.', 'خذ خطوة لقدام وانزل لين الركبتين 90 درجة.', 'ادفع بالرجل الأمامية وارجع، وبعدها الرجل الثانية.'],
      ['Stand with the dumbbells at your sides.', 'Step forward and lower until both knees are about 90°.', 'Push off the front foot to return, then switch legs.'],
      ['خطوة قصيرة فتطلع الركبة بعيد قدام.', 'الركبة الأمامية تدخل لجوا.'],
      ['A short step that pushes the front knee far forward.', 'The front knee caving in.']],
    ex_55: ['فخذ أمامي، مقعدة', 'Quads, glutes',
      ['حط مشط رجلك الخلفية على بنش، والأمامية بعيدة خطوة كبيرة.', 'انزل لين فخذك الأمامي موازي للأرض.', 'ادفع بالرجل الأمامية وقوم.'],
      ['Rest the top of your back foot on a bench, front foot a big step away.', 'Lower until your front thigh is parallel to the floor.', 'Drive through the front foot to stand.'],
      ['الرجل الأمامية قريبة زيادة.', 'تدفع بالرجل الخلفية.'],
      ['Front foot too close to the bench.', 'Pushing with the back leg.']],
    ex_56: ['الفخذ الداخلي والخارجي، مقعدة', 'Inner and outer thighs, glutes',
      ['اجلس وظهرك على المسند، والوسائد على جنب ركبتك.', 'افتح رجولك (إبعاد) أو ضمها (ضم) ببطء.', 'رجّع بتحكم بدون ما يلمس الوزن.'],
      ['Sit with your back on the pad and the pads against your knees.', 'Push your legs apart (abduction) or together (adduction) slowly.', 'Return under control without touching the stack.'],
      ['ترجع بسرعة.', 'تتمرجح بالجذع.'],
      ['Letting the weight snap back.', 'Rocking your torso.']],
    ex_57: ['مقعدة، فخذ خلفي', 'Glutes, hamstrings',
      ['ظهرك على المسند والحزام على الورك، ورجولك بعرض الكتف.', 'ادفع الورك لفوق لين يصير جسمك مستقيم من الكتف للركبة، وعصّر المقعدة.', 'نزّل ببطء.'],
      ['Back on the pad, belt over your hips, feet shoulder-width.', 'Drive your hips up until your body is straight from shoulders to knees, squeeze your glutes.', 'Lower slowly.'],
      ['تقوس أسفل ظهرك فوق.', 'رجولك بعيدة فتشتغل الخلفية بدل المقعدة.'],
      ['Arching your lower back at the top.', 'Feet so far out the hamstrings take over.']],
    ex_58: ['سمانة', 'Calves',
      ['قف ومشط رجلك على طرف المنصة، والكتف تحت الوسائد.', 'ارفع كعبك لأعلى نقطة وثبّت ثانية.', 'نزّل كعبك تحت مستوى المنصة لين تحس بتمدد.'],
      ['Stand with the balls of your feet on the edge, shoulders under the pads.', 'Rise as high as you can and hold a second.', 'Lower your heels below the platform to a stretch.'],
      ['تنط بسرعة.', 'تثني الركبة.'],
      ['Bouncing quickly.', 'Bending your knees.']],
    ex_59: ['سمانة (السولية)', 'Calves (soleus)',
      ['اجلس والوسادة على فخذك، ومشط رجلك على المنصة.', 'ارفع كعبك لأعلى نقطة.', 'نزّل ببطء لين تمدد كامل.'],
      ['Sit with the pad on your thighs and the balls of your feet on the platform.', 'Lift your heels as high as you can.', 'Lower slowly to a full stretch.'],
      ['حركة قصيرة.', 'تستعجل.'],
      ['A short range of motion.', 'Rushing the reps.']],
    ex_60: ['عضلات البطن', 'Abs',
      ['استلق وركبتك مثنية، ويدك جنب رأسك.', 'ارفع كتفك عن الأرض وأنت تقرب صدرك لحوضك.', 'نزّل ببطء.'],
      ['Lie down, knees bent, hands beside your head.', 'Curl your shoulders off the floor, bringing your ribs toward your hips.', 'Lower slowly.'],
      ['تسحب رأسك بيدك.', 'تقوم بالكامل وتشتغل عضلة الورك.'],
      ['Pulling on your head with your hands.', 'Sitting all the way up so the hip flexors take over.']],
    ex_61: ['أسفل البطن، عضلة الورك', 'Lower abs, hip flexors',
      ['تعلّق في البار وجسمك ثابت.', 'ارفع رجولك لين فخذك فوق مستوى الورك، وحوضك يلف لفوق.', 'نزّل ببطء بدون مرجحة.'],
      ['Hang from the bar with your body still.', 'Raise your legs until your thighs pass hip height, tilting your pelvis up.', 'Lower slowly without swinging.'],
      ['تتمرجح.', 'ترفع الرجل بدون ما يلف الحوض.'],
      ['Swinging.', 'Lifting the legs without tilting the pelvis.']],
    ex_62: ['البطن وثبات الجذع', 'Abs and core',
      ['ساعدك على الأرض تحت كتفك، وجسمك مستقيم من الرأس للكعب.', 'شد بطنك ومقعدتك وتنفس عادي.', 'اثبت للوقت المحدد، ووقف لما يبدأ الورك ينزل.'],
      ['Forearms under your shoulders, body straight from head to heels.', 'Brace your abs and glutes and keep breathing.', 'Hold for the set time; stop when your hips start to sag.'],
      ['الورك ينزل أو يرتفع.', 'تحبس نفسك.'],
      ['Letting the hips sag or pike up.', 'Holding your breath.']],
    ex_63: ['عضلات البطن', 'Abs',
      ['اركع قدام الكيبل وامسك الحبل جنب رأسك.', 'انحني لتحت بقوة البطن، والكوع يقرب من ركبتك.', 'ارجع ببطء.'],
      ['Kneel in front of the cable holding the rope beside your head.', 'Crunch down with your abs, elbows toward your knees.', 'Return slowly.'],
      ['تسحب بيدك.', 'تجلس على كعبك وتحرك من الورك.'],
      ['Pulling with your arms.', 'Sitting back and moving from the hips.']],
    ex_64: ['قلب ورئة، رجول', 'Heart and lungs, legs',
      ['ابدأ بمشي 3–5 دقايق تسخين.', 'اختار سرعة تقدر تتكلم فيها بجمل قصيرة، أو زد الميلان بدل السرعة.', 'آخر 3 دقايق خفف السرعة تدريجيًا.'],
      ['Start with 3–5 minutes of walking to warm up.', 'Choose a pace where you can speak in short sentences, or add incline instead of speed.', 'Ease the speed down over the last 3 minutes.'],
      ['تمسك المقابض وأنت على ميلان عالي.', 'تنزل من الجهاز وهو شغال.'],
      ['Holding the rails on a steep incline.', 'Stepping off while the belt is still moving.']],
    ex_65: ['قلب ورئة، رجول', 'Heart and lungs, legs',
      ['اضبط المقعد لين ركبتك مثنية شوي تحت.', 'ابدأ بمقاومة خفيفة 3 دقايق.', 'زد المقاومة لين يصير التنفس أسرع بس تقدر تتكلم.'],
      ['Set the seat so your knee is slightly bent at the bottom.', 'Start with light resistance for 3 minutes.', 'Raise resistance until breathing is faster but you can still talk.'],
      ['المقعد منخفض فتضغط على الركبة.', 'مقاومة صفر وسرعة عالية جدًا.'],
      ['A seat so low it strains your knees.', 'Zero resistance and frantic pedalling.']],
    ex_66: ['قلب ورئة، جسم كامل', 'Heart and lungs, full body',
      ['اوقف بثبات وامسك المقابض المتحركة.', 'ادفع واسحب بيدك مع حركة رجلك.', 'زد المقاومة بدل السرعة.'],
      ['Stand tall and hold the moving handles.', 'Push and pull with your arms as your legs move.', 'Raise resistance rather than speed.'],
      ['تتكي على المقابض.', 'ترفع كعبك طول الوقت.'],
      ['Leaning on the handles.', 'Staying up on your toes the whole time.']],
    ex_67: ['قلب ورئة، مقعدة، رجول', 'Heart and lungs, glutes, legs',
      ['اوقف مستقيم وحط يدك خفيف على المقابض.', 'اطلع الدرجة كاملة بكل رجلك.', 'ابدأ بسرعة بطيئة وزدها تدريجيًا.'],
      ['Stand tall with a light touch on the rails.', 'Step onto each stair with your whole foot.', 'Start slow and build up.'],
      ['تتكي بثقلك على المقابض.', 'تنحني لقدام.'],
      ['Hanging your weight on the rails.', 'Hunching forward.']],
    ex_68: ['قلب ورئة، ظهر، رجول', 'Heart and lungs, back, legs',
      ['ابدأ برجولك، بعدها ميّل جسمك لورا شوي، وآخر شي اسحب بيدك لبطنك.', 'ارجع بالعكس: يدك، بعدها جسمك، بعدها رجولك.', 'خل الضربة قوية والرجوع هادي.'],
      ['Push with your legs first, then lean back slightly, then pull the handle to your belly.', 'Return in reverse: arms, then body, then legs.', 'Make the drive strong and the return relaxed.'],
      ['تسحب بيدك قبل رجولك.', 'تدوّر ظهرك.'],
      ['Pulling with your arms before your legs.', 'Rounding your back.']],
    ex_69: ['قلب ورئة، جسم كامل', 'Heart and lungs, full body',
      ['اضبط المقعد مثل الدراجة العادية.', 'ادفع وارجع بيدك ورجولك مع بعض.', 'استخدمها بفترات: 20 ثانية قوية و40 ثانية هادية.'],
      ['Set the seat like a normal bike.', 'Push and pull with arms and legs together.', 'Use intervals: 20 seconds hard, 40 seconds easy.'],
      ['تبدأ بأقصى جهد بدون تسخين.', 'تنحني على المقابض.'],
      ['Going all-out without a warm-up.', 'Slumping over the handles.']],
    ex_70: ['فخذ خلفي، مقعدة، ظهر، ترابيس', 'Hamstrings, glutes, back, traps',
      ['البار فوق منتصف رجلك، وامسكه والظهر مستقيم والصدر مرفوع.', 'شد بطنك وادفع الأرض برجولك، والبار يطلع لاصق بساقك وفخذك.', 'اوقف مستقيم فوق بدون ما تميل لورا، ونزّله بنفس الطريق.'],
      ['Bar over mid-foot; grip it with a flat back and chest up.', 'Brace and push the floor away, the bar dragging up your shins and thighs.', 'Stand tall without leaning back, then lower it the same way.'],
      ['تدوّر ظهرك.', 'البار يبعد عن رجلك.'],
      ['Rounding your back.', 'Letting the bar drift away from your legs.']]
  };

  function get(id) {
    var g = G[id];
    if (!g) return null;
    var en = !!window.GymI18n && window.GymI18n.lang === 'en';
    return { muscles: en ? g[1] : g[0], steps: en ? g[3] : g[2], mistakes: en ? g[5] : g[4] };
  }
  window.GymGuide = { get: get, ids: function () { return Object.keys(G); } };
})();
